In [1]:
#Importing the necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
#opening the csv file and converting to DataFrame
df = pd.read_csv('car_details.csv')

In [3]:
df.head()

vehical_name Registration Year      Insurance   \
0                    2013 Toyota Etios GD               2013              -   
1                    2024 Toyota Glanza V               2024              -   
2           2017 Hyundai Creta 1.4 E Plus             Jul-17  Comprehensive   
3  2011 Volkswagen Vento Diesel Trendline               2011              -   
4             2014 Hyundai Verna 1.6 CRDI               2014              -   

  Fuel Type    Seats    Kms Driven             RTO     Ownership   \
0     Diesel  5 Seats  1,50,000 Kms  Sri Ganganagar  Fourth Owner   
1     Petrol  5 Seats    10,000 Kms          dasuya   First Owner   
2     Diesel  5 Seats    75,000 Kms         Gurgaon   First Owner   
3     Diesel  5 Seats  1,60,000 Kms       jalalabad   Third Owner   
4     Diesel  5 Seats  1,20,000 Kms          Meerut   First Owner   

  Engine Displacement  Transmission   Year of Manufacture   Engine   \
0              1364 cc        Manual                2013.0      NaN   
1              1197 cc        Manual                2024.0      NaN   
2              1396 cc        Manual                2017.0      NaN   
3              1598 cc        Manual                2011.0  1598 cc   
4              1582 cc        Manual                2014.0  1582 cc   

      Power  Transmission .1 Drive Type     Mileage    Fuel   \
0        NaN          Manual         NaN         NaN     NaN   
1        NaN          Manual         NaN         NaN     NaN   
2        NaN          Manual         NaN         NaN     NaN   
3  103.6 bhp          Manual         NaN  20.54 kmpl  Diesel   
4  126.3 bhp          Manual         NaN  22.32 kmpl  Diesel   

           new_vehical_price               vehical_price  \
0   New Car Price ₹8.05 Lakh                 ₹2.60 Lakh    
1  New Car Price ₹11.28 Lakh                 ₹9.40 Lakh    
2  New Car Price ₹11.86 Lakh  ₹6.25 Lakh Make Your Offer   
3  New Car Price ₹10.05 Lakh                 ₹1.40 Lakh    
4  New Car Price ₹11.87 Lakh                    ₹4 Lakh    

                                     other_features  
0                                                []  
1                                                []  
2                                                []  
3                               ['Parking Sensors']  
4  ['Automatic Climate Control', 'Parking Sensors']

In [4]:
df.shape

(10224, 20)

### Dataset Summary

This dataset consists of 10,224 rows and 20 columns, where each row represents an individual used car listed for sale. The dataset includes detailed information such as the car’s brand, model, year of manufacture, fuel type, transmission type, engine capacity, mileage, location, and selling price. It provides a comprehensive view of the used car market, making it useful for analyzing pricing trends, identifying factors that influence car prices, and building predictive models for estimating the resale value of vehicles.

### Columns Description

| **Column Name**         | **Description**                                                                                              |
| ----------------------- | ------------------------------------------------------------------------------------------------------------ |
| **vehical_name**        | The full name of the car, typically including year, brand, and model.                                        |
| **Registration Year**   | The year in which the vehicle was registered with the RTO.                                                   |
| **Insurance**           | Type or status of car insurance (e.g., Comprehensive, Third-Party, or missing).                              |
| **Fuel Type**           | The primary fuel used by the car (e.g., Petrol, Diesel, CNG).                                                |
| **Seats**               | Total number of seats in the car (e.g., 5 Seats, 7 Seats).                                                   |
| **Kms Driven**          | The total distance the car has been driven, often formatted as text (e.g., “75,000 Kms”).                    |
| **RTO**                 | The Regional Transport Office (RTO) location where the vehicle is registered.                                |
| **Ownership**           | Ownership type indicating how many people have owned the vehicle (e.g., First Owner, Second Owner).          |
| **Engine Displacement** | Engine capacity in cubic centimeters (cc), showing the engine’s power potential.                             |
| **Transmission**        | Type of transmission in the vehicle (e.g., Manual, Automatic).                                               |
| **Year of Manufacture** | The year the car was originally manufactured.                                                                |
| **Engine**              | Engine specification, often redundant with engine displacement but sometimes includes details like cc value. |
| **Power**               | Maximum power output of the vehicle, generally measured in brake horsepower (bhp).                           |
| **Transmission .1**     | Duplicate or alternative transmission column, likely due to data extraction; may need cleaning.              |
| **Drive Type**          | Indicates drivetrain type (e.g., FWD, RWD, AWD). Often missing or unrecorded.                                |
| **Mileage**             | The fuel efficiency of the car, typically in kmpl (kilometers per liter).                                    |
| **Fuel**                | Duplicate or secondary fuel column similar to “Fuel Type.”                                                   |
| **new_vehical_price**   | The price of a brand-new version of the same model, usually listed as text with currency symbols.            |
| **vehical_price**       | The current selling price of the used car (target variable for price prediction).                            |
| **other_features**      | List of extra features like “Parking Sensors,” “Climate Control,” etc., represented as text or lists.        |


## Data Accessing

- **Manual assessment :** Looking through the data manually in google sheets
- **Programmatic assessment :** By using pandas functions such as info(), describe() or sample()

In [5]:
#Programmatic assessment
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10224 entries, 0 to 10223
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   vehical_name          10224 non-null  object 
 1   Registration Year     10198 non-null  object 
 2   Insurance             10224 non-null  object 
 3   Fuel Type             10224 non-null  object 
 4   Seats                 10212 non-null  object 
 5   Kms Driven            10224 non-null  object 
 6   RTO                   9557 non-null   object 
 7   Ownership             10221 non-null  object 
 8   Engine Displacement   10138 non-null  object 
 9   Transmission          10224 non-null  object 
 10  Year of Manufacture   10201 non-null  float64
 11  Engine                7341 non-null   object 
 12  Power                 7098 non-null   object 
 13  Transmission .1       10224 non-null  object 
 14  Drive Type            2247 non-null   object 
 15  Mileage            

In [6]:
#checking for no.of null values in each col
df.isnull().sum()

vehical_name               0
Registration Year         26
Insurance                  0
Fuel Type                  0
Seats                     12
Kms Driven                 0
RTO                      667
Ownership                  3
Engine Displacement       86
Transmission               0
Year of Manufacture       23
Engine                  2883
Power                   3126
Transmission .1            0
Drive Type              7977
Mileage                 3415
Fuel                    4064
new_vehical_price          0
vehical_price              0
other_features             0
dtype: int64

In [7]:
missing_percentage = (df.isnull().sum() / len(df)) * 100
missing_percentage

vehical_name             0.000000
Registration Year        0.254304
Insurance                0.000000
Fuel Type                0.000000
Seats                    0.117371
Kms Driven               0.000000
RTO                      6.523865
Ownership                0.029343
Engine Displacement      0.841158
Transmission             0.000000
Year of Manufacture      0.224961
Engine                  28.198357
Power                   30.575117
Transmission .1          0.000000
Drive Type              78.022300
Mileage                 33.401800
Fuel                    39.749609
new_vehical_price        0.000000
vehical_price            0.000000
other_features           0.000000
dtype: float64

In [8]:
df.duplicated().sum()

np.int64(79)

In [9]:
df.describe()

Year of Manufacture 
count          10201.000000
mean            2017.599157
std                4.498954
min             2002.000000
25%             2014.000000
50%             2018.000000
75%             2021.000000
max             2025.000000

In [10]:
(df['Insurance '].value_counts()/len(df))*100

Insurance 
-                79.303599
Comprehensive    16.656886
Third Party       3.139671
Zero Dep          0.899844
Name: count, dtype: float64

In [2]:
pd.set_option('display.max_rows', None)

## Issues with the dataset

- Mileage column has Inconsistent units for some records it is kmpl (Kilometers per Liter for Petrol/Diesel) and for some it is km/kg (Kilometers per Kilogram for CNG/LPG).
- The values in Engine Displacement and Engine (where both are present) are identical, indicating they represent the same feature.
- There are 79 duplicate records in dataset.
- In Insurance column 79% of the values are represnted by '-' which has to be null.
- The values in Fuel and Fuel_type (where both are present) are identical, indicating they represent the same feature.
- Transmission column is present 2 times with two names.
- The Registration Year column contains mixed formats — some entries have only the year (e.g., 2013), while others include month and year (e.g., Jul-17).And also it has 0.26% missing values.
- The Seats column has approximately 0.12% missing values, which represent cars where seating capacity was not recorded.
- The Kms Driven column contains string values with text like "kms" and commas (e.g., "45,000 kms"), making it non-numeric and unsuitable for numerical operations.
- The RTO column represents the Regional Transport Office where the vehicle is registered. However, some records contain only partial information (e.g., "MH12", "TS09") showing only the first four letters of the vehicle number plate, while others include the full RTO city or office name. Additionally, around 6.52% of the values are missing (null).
- Ownership column as 3 missing values.
- Engine Displacement has around 0.84% missing values.
- Year of Manufactore column values are almost same as Registration_year.
- Power column as 30.5% missing values.
- The Drive Type column indicates the vehicle’s drivetrain (e.g., FWD, RWD, AWD, 4WD) but contains inconsistent formats like *‘4X4’, ‘Four Whell Drive’, ‘RWD(with MTT)’*. It also has 78% missing values, affecting data consistency.
-  Mileage has 33.4% null values.
-  The ‘New Car Price’ column contains text such as ‘New Car Price ₹11.28 Lakh’, which includes unnecessary words and currency symbols. We need to extract only the numeric price values and convert them into float type for proper numerical analysis.
- The ‘Vehicle Price’ column contains inconsistent formats — some entries include extra text like “Make Your Offer”, while others are expressed in lakhs or thousands.
- The ‘other_features’ column contains lists of car features in inconsistent formats — some records have empty lists ([]), while others include multiple features as string lists.

### Data Cleaning

#### Steps involved in Data cleaning
- Define
- Code
- Test

In [29]:
#1. Removing the duplicate columns Fuel,transmission1,year of manufactore,Engine
df.drop(columns=['Year of Manufacture ','Engine ','Fuel ','Transmission .1'],inplace=True)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10224 entries, 0 to 10223
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   vehical_name          10224 non-null  object
 1   Registration Year     10198 non-null  object
 2   Insurance             10224 non-null  object
 3   Fuel Type             10224 non-null  object
 4   Seats                 10212 non-null  object
 5   Kms Driven            10224 non-null  object
 6   RTO                   9557 non-null   object
 7   Ownership             10221 non-null  object
 8   Engine Displacement   10138 non-null  object
 9   Transmission          10224 non-null  object
 10  Power                 7098 non-null   object
 11  Drive Type            2247 non-null   object
 12  Mileage               6809 non-null   object
 13  new_vehical_price     10224 non-null  object
 14  vehical_price         10224 non-null  object
 15  other_features        10224 non-null

In [37]:
#changing col names to lowercase
df.columns = df.columns.str.strip()

df.rename(columns={
    'vehical_name': 'vehicle_name',
    'Registration Year': 'registration_year',
    'Insurance': 'insurance_status',
    'Fuel Type': 'fuel_type',
    'Seats': 'seats',
    'Kms Driven': 'kms_driven',
    'RTO': 'rto_location',
    'Ownership': 'ownership',
    'Engine Displacement': 'engine_displacement',
    'Transmission': 'transmission_type',
    'Power': 'engine_power',
    'Drive Type': 'drive_type',
    'Mileage': 'mileage',
    'new_vehical_price': 'new_vehicle_price',
    'vehical_price': 'vehicle_price',
    'other_features': 'other_features'
}, inplace=True)

In [29]:
df = pd.read_csv('cars_updated.csv',index_col=0)

In [30]:
df.head()

vehicle_name registration_year insurance_status  \
0                    2013 Toyota Etios GD              2013                -   
1                    2024 Toyota Glanza V              2024                -   
2           2017 Hyundai Creta 1.4 E Plus            Jul-17    Comprehensive   
3  2011 Volkswagen Vento Diesel Trendline              2011                -   
4             2014 Hyundai Verna 1.6 CRDI              2014                -   

  fuel_type    seats    kms_driven    rto_location     ownership  \
0    Diesel  5 Seats  1,50,000 Kms  Sri Ganganagar  Fourth Owner   
1    Petrol  5 Seats    10,000 Kms          dasuya   First Owner   
2    Diesel  5 Seats    75,000 Kms         Gurgaon   First Owner   
3    Diesel  5 Seats  1,60,000 Kms       jalalabad   Third Owner   
4    Diesel  5 Seats  1,20,000 Kms          Meerut   First Owner   

  engine_displacement transmission_type engine_power drive_type     mileage  \
0             1364 cc            Manual          NaN        NaN         NaN   
1             1197 cc            Manual          NaN        NaN         NaN   
2             1396 cc            Manual          NaN        NaN         NaN   
3             1598 cc            Manual    103.6 bhp        NaN  20.54 kmpl   
4             1582 cc            Manual    126.3 bhp        NaN  22.32 kmpl   

           new_vehicle_price               vehicle_price  \
0   New Car Price ₹8.05 Lakh                 ₹2.60 Lakh    
1  New Car Price ₹11.28 Lakh                 ₹9.40 Lakh    
2  New Car Price ₹11.86 Lakh  ₹6.25 Lakh Make Your Offer   
3  New Car Price ₹10.05 Lakh                 ₹1.40 Lakh    
4  New Car Price ₹11.87 Lakh                    ₹4 Lakh    

                                     other_features  
0                                                []  
1                                                []  
2                                                []  
3                               ['Parking Sensors']  
4  ['Automatic Climate Control', 'Parking Sensors']

#### Mileage :

In [31]:
# In mileage converting every record into kmpl and converting it into float
df['mileage'].unique()

array([nan, '20.54 kmpl', '22.32 kmpl', '13.45 km/kg', '16.35 kmpl',
       '21.5 kmpl', '21.38 kmpl', '15.96 kmpl', '16 kmpl', '24.3 kmpl',
       '21.21 kmpl', '20.6 kmpl', '21.13 kmpl', '28.09 kmpl', '17 kmpl',
       '19.33 kmpl', '24.2 kmpl', '19.3 kmpl', '18.6 kmpl', '26.59 kmpl',
       '26.2 km/kg', '18.49 kmpl', '16.36 kmpl', '18.27 kmpl', '20 kmpl',
       '19.67 kmpl', '26.8 kmpl', '21 kmpl', '17.4 kmpl', '23.59 kmpl',
       '22.1 kmpl', '24.8 kmpl', '19.44 kmpl', '22.38 kmpl', '19.2 kmpl',
       '22.5 kmpl', '27.97 kmpl', '25.8 kmpl', '20.09 kmpl', '20.36 kmpl',
       '24 kmpl', '22.54 kmpl', '16.1 kmpl', '23 kmpl', '17.03 kmpl',
       '16.25 kmpl', '15.42 kmpl', '12.8 kmpl', '22.7 kmpl', '18.1 kmpl',
       '17.71 kmpl', '15.2 kmpl', '26.21 kmpl', '25.44 kmpl', '11.5 kmpl',
       '21.11 kmpl', '15.4 kmpl', '18.4 kmpl', '15.9 kmpl', '20.4 kmpl',
       '21.01 kmpl', '21.1 kmpl', '17.8 kmpl', '18.15 kmpl', '19.01 kmpl',
       '17.5 kmpl', '9.5 kmpl', '21.4 kmpl', '18 k

In [32]:
df['mileage_value'] = df['mileage'].str.split(' ').str.get(0)
df['mileage_unit'] = df['mileage'].str.split(' ').str.get(1)

In [33]:
df['mileage_unit'].unique()

array([nan, 'kmpl', 'km/kg'], dtype=object)

In [34]:
df['fuel_type'].value_counts()

fuel_type
Petrol      5563
Diesel      4209
CNG          330
Electric      82
LPG           40
Name: count, dtype: int64

In [35]:
df['mileage_value'] = df['mileage_value'].astype('float')

In [36]:
# Conditional conversion from km/kg → kmpl based on fuel type (avoiding the null values)
df.loc[(df['fuel_type'] == 'Petrol') & 
       (df['mileage_unit'] == 'km/kg') & 
       (df['mileage_value'].notnull()), 'mileage_value'] /= 1.39

df.loc[(df['fuel_type'] == 'Diesel') & 
       (df['mileage_unit'] == 'km/kg') & 
       (df['mileage_value'].notnull()), 'mileage_value'] /= 1.18

df.loc[(df['fuel_type'] == 'LPG') & 
       (df['mileage_unit'] == 'km/kg') & 
       (df['mileage_value'].notnull()), 'mileage_value'] /= 1.25


In [45]:
df[df['fuel_type'] == 'Electric']['mileage'].isnull().sum()

np.int64(82)

In [40]:
df.loc[df['fuel_type'] == 'Electric','mileage_value'] = 0

In [43]:
df[df['fuel_type'] == 'Electric']['mileage_value']

418      0.0
452      0.0
565      0.0
622      0.0
655      0.0
        ... 
9548     0.0
9557     0.0
9560     0.0
9794     0.0
10011    0.0
Name: mileage_value, Length: 82, dtype: float64

In [47]:
#droping cols mileage & mileage_unit
df.drop(columns=['mileage_unit','mileage'],inplace=True)

In [50]:
#changing the mileage_value col name
df.rename(columns={'mileage_value':'mileage(kmpl)'},inplace=True)

In [51]:
df['mileage(kmpl)'].describe()

count    6891.000000
mean       19.691790
std         4.432978
min         0.000000
25%        17.110000
50%        19.810000
75%        22.365000
max        35.600000
Name: mileage(kmpl), dtype: float64

#### Registration_year :

In [60]:
df.head()

vehicle_name registration_year insurance_status  \
0                    2013 Toyota Etios GD              2013                -   
1                    2024 Toyota Glanza V              2024                -   
2           2017 Hyundai Creta 1.4 E Plus            Jul-17    Comprehensive   
3  2011 Volkswagen Vento Diesel Trendline              2011                -   
4             2014 Hyundai Verna 1.6 CRDI              2014                -   

  fuel_type    seats    kms_driven    rto_location     ownership  \
0    Diesel  5 Seats  1,50,000 Kms  Sri Ganganagar  Fourth Owner   
1    Petrol  5 Seats    10,000 Kms          dasuya   First Owner   
2    Diesel  5 Seats    75,000 Kms         Gurgaon   First Owner   
3    Diesel  5 Seats  1,60,000 Kms       jalalabad   Third Owner   
4    Diesel  5 Seats  1,20,000 Kms          Meerut   First Owner   

  engine_displacement transmission_type engine_power drive_type  \
0             1364 cc            Manual          NaN        NaN   
1             1197 cc            Manual          NaN        NaN   
2             1396 cc            Manual          NaN        NaN   
3             1598 cc            Manual    103.6 bhp        NaN   
4             1582 cc            Manual    126.3 bhp        NaN   

           new_vehicle_price               vehicle_price  \
0   New Car Price ₹8.05 Lakh                 ₹2.60 Lakh    
1  New Car Price ₹11.28 Lakh                 ₹9.40 Lakh    
2  New Car Price ₹11.86 Lakh  ₹6.25 Lakh Make Your Offer   
3  New Car Price ₹10.05 Lakh                 ₹1.40 Lakh    
4  New Car Price ₹11.87 Lakh                    ₹4 Lakh    

                                     other_features  mileage(kmpl)  
0                                                []            NaN  
1                                                []            NaN  
2                                                []            NaN  
3                               ['Parking Sensors']          20.54  
4  ['Automatic Climate Control', 'Parking Sensors']          22.32

In [71]:
df['registration_year'].unique()

array(['2013', '2024', 'Jul-17', '2011', '2014', '2012', 'May-23',
       'Jul-21', 'Jul-19', 'Jan-19', 'Apr-14', 'Aug-17', 'Jul-18',
       'Dec-20', 'Aug-14', 'Oct-21', 'Jul-14', 'Dec-17', 'Dec-16',
       'Mar-11', 'Feb-15', 'Apr-11', 'Jun-12', 'Mar-15', 'Oct-10',
       'Aug-16', 'Feb-20', 'Aug-12', 'Nov-24', 'Jan-15', 'May-16',
       'Mar-17', 'Nov-13', 'Dec-15', 'May-15', 'Apr-13', 'Jan-12',
       'Oct-12', 'Nov-18', 'May-14', 'Nov-21', '2017', 'Sep-14', '2023',
       '2010', '2019', 'Aug-11', 'Nov-22', '2015', '2016', '2020', '2025',
       'Jul-15', 'Feb-23', 'May-10', 'Mar-10', 'Feb-11', 'Aug-18',
       'Nov-11', 'Aug-09', 'Sep-13', 'Sep-21', 'May-19', 'Oct-22',
       'Aug-20', 'May-07', 'Oct-11', 'Jun-16', '2021', 'Aug-23', '2022',
       'Jan-17', 'Nov-19', 'Nov-10', 'Apr-18', 'May-11', 'Jun-23',
       'Jun-20', 'Jul-12', 'Apr-19', 'Mar-20', 'Jan-16', 'Mar-19',
       'May-18', 'Aug-15', 'Jan-18', 'Apr-17', 'Mar-18', 'Jun-18',
       'Oct-17', 'Dec-11', 'May-17', 'Sep-

In [72]:
#cleaning registration_year column and making every value in it to same format
def clean_registration_year(value):
    try:
        value = str(value).strip()
        #Case 1: if it's already a 4-digit year
        if value.isdigit() and len(value) == 4:
            return int(value)
        
        #Case 2: if format like "Aug-17" or "Jul-21"
        elif "-" in value:
            year_part = value.split("-")[-1]
            if len(year_part) == 2:
                year = int("20" + year_part) if int(year_part) <= 25 else int("19" + year_part)
                return year
        
        # Otherwise return NaN
        return np.nan
    
    except:
        return np.nan

# Apply the function
df['registration_year_cleaned'] = df['registration_year'].apply(clean_registration_year)

In [74]:
df['registration_year_cleaned'] = df['registration_year_cleaned'].astype('Int64')

In [76]:
#droping registation_year col
df.drop(columns=['registration_year'],inplace=True)

In [78]:
df.rename(columns={'registration_year_cleaned':'registration_year'},inplace=True)

In [79]:
df['registration_year'].value_counts()

registration_year
2017    841
2023    824
2022    824
2018    806
2021    805
2016    741
2019    724
2024    645
2015    619
2014    611
2020    590
2013    479
2012    436
2011    364
2010    285
2025    206
2009    132
2008     85
2007     61
2006     56
2005     23
2004     20
2003     13
2002      8
Name: count, dtype: Int64

In [92]:
df['registration_year'] = df['registration_year'].astype('Int64')

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10224 entries, 0 to 10223
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   vehicle_name         10224 non-null  object 
 1   insurance_status     10224 non-null  object 
 2   fuel_type            10224 non-null  object 
 3   seats                10212 non-null  object 
 4   kms_driven           10224 non-null  object 
 5   rto_location         9557 non-null   object 
 6   ownership            10221 non-null  object 
 7   engine_displacement  10138 non-null  object 
 8   transmission_type    10224 non-null  object 
 9   engine_power         7098 non-null   object 
 10  drive_type           2247 non-null   object 
 11  new_vehicle_price    10224 non-null  object 
 12  vehicle_price        10224 non-null  object 
 13  other_features       10224 non-null  object 
 14  mileage(kmpl)        6891 non-null   float64
 15  registration_year    10198 non-null  Int6

In [94]:
#handling null values with the registration_year which is presnet in vehicle_name col
temp_df = df[df['registration_year'].isnull()]

In [95]:
df.loc[temp_df.index,'registration_year'] = temp_df['vehicle_name'].str.strip().str.split(' ').str.get(0)

In [96]:
#checking 
df[['vehicle_name','registration_year']].sample(10)

vehicle_name  registration_year
7341                         2025 MG Astor Shine               2025
5130   2014 Volkswagen Polo Diesel Highline 1.2L               2014
5166                    2017 Maruti Alto 800 VXI               2017
6101         2019 MG Hector Sharp Diesel MT BSIV               2019
5605              2011 Ford Figo Diesel Titanium               2011
9438         2025 Mahindra Bolero Neo N10 Option               2025
1101                       2021 Maruti Swift VXI               2021
4801              2015 Hyundai Xcent 1.2 Kappa S               2015
10016                2017 Maruti Wagon R LXI CNG               2017
5290                  2016 Honda Amaze SX i DTEC               2016

In [97]:
df['registration_year'].value_counts()

registration_year
2017    841
2022    824
2023    824
2018    806
2021    805
2016    741
2019    724
2024    647
2015    619
2014    611
2020    590
2013    479
2012    436
2011    364
2010    285
2025    207
2009    132
2008     85
2007     61
2006     56
2005     23
2004     20
2003     13
2002      8
2001      8
2000      4
1998      3
1991      3
1985      1
1999      1
1995      1
1997      1
1996      1
Name: count, dtype: Int64

In [4]:
df = pd.read_csv('cars_updated_data.csv',index_col=0)

In [5]:
df.head()

vehicle_name insurance_status fuel_type    seats  \
0                    2013 Toyota Etios GD                -    Diesel  5 Seats   
1                    2024 Toyota Glanza V                -    Petrol  5 Seats   
2           2017 Hyundai Creta 1.4 E Plus    Comprehensive    Diesel  5 Seats   
3  2011 Volkswagen Vento Diesel Trendline                -    Diesel  5 Seats   
4             2014 Hyundai Verna 1.6 CRDI                -    Diesel  5 Seats   

     kms_driven    rto_location     ownership engine_displacement  \
0  1,50,000 Kms  Sri Ganganagar  Fourth Owner             1364 cc   
1    10,000 Kms          dasuya   First Owner             1197 cc   
2    75,000 Kms         Gurgaon   First Owner             1396 cc   
3  1,60,000 Kms       jalalabad   Third Owner             1598 cc   
4  1,20,000 Kms          Meerut   First Owner             1582 cc   

  transmission_type engine_power drive_type          new_vehicle_price  \
0            Manual          NaN        NaN   New Car Price ₹8.05 Lakh   
1            Manual          NaN        NaN  New Car Price ₹11.28 Lakh   
2            Manual          NaN        NaN  New Car Price ₹11.86 Lakh   
3            Manual    103.6 bhp        NaN  New Car Price ₹10.05 Lakh   
4            Manual    126.3 bhp        NaN  New Car Price ₹11.87 Lakh   

                vehicle_price  \
0                 ₹2.60 Lakh    
1                 ₹9.40 Lakh    
2  ₹6.25 Lakh Make Your Offer   
3                 ₹1.40 Lakh    
4                    ₹4 Lakh    

                                     other_features  mileage(kmpl)  \
0                                                []            NaN   
1                                                []            NaN   
2                                                []            NaN   
3                               ['Parking Sensors']          20.54   
4  ['Automatic Climate Control', 'Parking Sensors']          22.32   

   registration_year  
0               2013  
1               2024  
2               2017  
3               2011  
4               2014

#### Vehicle_name :

In [6]:
df['brand'] = df['vehicle_name'].str.split(' ').str.get(1)

In [7]:
df['model'] = df['vehicle_name'].str.split(' ').str.get(2)

In [8]:
temp_df = df[df['model'].str.len() < 2]

In [9]:
df.loc[temp_df.index,'model'] = df.loc[temp_df.index,'model'] + ' ' + temp_df['vehicle_name'].str.split(' ').str.get(3)

In [10]:
df['brand'].value_counts()

brand
Maruti           3111
Hyundai          1839
Mahindra          981
Tata              874
Honda             523
Toyota            447
Renault           388
Kia               334
Ford              321
Volkswagen        199
MG                166
Skoda             155
Mercedes-Benz     137
Audi              137
BMW               131
Chevrolet         125
Nissan            103
Jeep               81
Datsun             34
Land               31
Jaguar             20
Volvo              20
Fiat               19
Citroen            11
Mitsubishi          9
Mini                7
Porsche             5
Lexus               3
Isuzu               3
Force               2
Ashok               2
Bentley             2
BYD                 1
Ferrari             1
Lamborghini         1
Ambassador          1
Name: count, dtype: int64

In [11]:
df.loc[df['brand'] == 'Mercedes-Benz', 'brand'] = 'Mercedes Benz'

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10224 entries, 0 to 10223
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   vehicle_name         10224 non-null  object 
 1   insurance_status     10224 non-null  object 
 2   fuel_type            10224 non-null  object 
 3   seats                10212 non-null  object 
 4   kms_driven           10224 non-null  object 
 5   rto_location         9557 non-null   object 
 6   ownership            10221 non-null  object 
 7   engine_displacement  10138 non-null  object 
 8   transmission_type    10224 non-null  object 
 9   engine_power         7098 non-null   object 
 10  drive_type           2247 non-null   object 
 11  new_vehicle_price    10224 non-null  object 
 12  vehicle_price        10224 non-null  object 
 13  other_features       10224 non-null  object 
 14  mileage(kmpl)        6891 non-null   float64
 15  registration_year    10224 non-null  int6

#### Insurance_status :

In [13]:
df.head()

vehicle_name insurance_status fuel_type    seats  \
0                    2013 Toyota Etios GD                -    Diesel  5 Seats   
1                    2024 Toyota Glanza V                -    Petrol  5 Seats   
2           2017 Hyundai Creta 1.4 E Plus    Comprehensive    Diesel  5 Seats   
3  2011 Volkswagen Vento Diesel Trendline                -    Diesel  5 Seats   
4             2014 Hyundai Verna 1.6 CRDI                -    Diesel  5 Seats   

     kms_driven    rto_location     ownership engine_displacement  \
0  1,50,000 Kms  Sri Ganganagar  Fourth Owner             1364 cc   
1    10,000 Kms          dasuya   First Owner             1197 cc   
2    75,000 Kms         Gurgaon   First Owner             1396 cc   
3  1,60,000 Kms       jalalabad   Third Owner             1598 cc   
4  1,20,000 Kms          Meerut   First Owner             1582 cc   

  transmission_type engine_power drive_type          new_vehicle_price  \
0            Manual          NaN        NaN   New Car Price ₹8.05 Lakh   
1            Manual          NaN        NaN  New Car Price ₹11.28 Lakh   
2            Manual          NaN        NaN  New Car Price ₹11.86 Lakh   
3            Manual    103.6 bhp        NaN  New Car Price ₹10.05 Lakh   
4            Manual    126.3 bhp        NaN  New Car Price ₹11.87 Lakh   

                vehicle_price  \
0                 ₹2.60 Lakh    
1                 ₹9.40 Lakh    
2  ₹6.25 Lakh Make Your Offer   
3                 ₹1.40 Lakh    
4                    ₹4 Lakh    

                                     other_features  mileage(kmpl)  \
0                                                []            NaN   
1                                                []            NaN   
2                                                []            NaN   
3                               ['Parking Sensors']          20.54   
4  ['Automatic Climate Control', 'Parking Sensors']          22.32   

   registration_year       brand   model  
0               2013      Toyota   Etios  
1               2024      Toyota  Glanza  
2               2017     Hyundai   Creta  
3               2011  Volkswagen   Vento  
4               2014     Hyundai   Verna

In [14]:
df['insurance_status'].value_counts()/len(df)*100

insurance_status
-                79.303599
Comprehensive    16.656886
Third Party       3.139671
Zero Dep          0.899844
Name: count, dtype: float64

In [15]:
df.drop(columns=['insurance_status'],axis=1,inplace=True)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10224 entries, 0 to 10223
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   vehicle_name         10224 non-null  object 
 1   fuel_type            10224 non-null  object 
 2   seats                10212 non-null  object 
 3   kms_driven           10224 non-null  object 
 4   rto_location         9557 non-null   object 
 5   ownership            10221 non-null  object 
 6   engine_displacement  10138 non-null  object 
 7   transmission_type    10224 non-null  object 
 8   engine_power         7098 non-null   object 
 9   drive_type           2247 non-null   object 
 10  new_vehicle_price    10224 non-null  object 
 11  vehicle_price        10224 non-null  object 
 12  other_features       10224 non-null  object 
 13  mileage(kmpl)        6891 non-null   float64
 14  registration_year    10224 non-null  int64  
 15  brand                10224 non-null  obje

#### Fuel_type

In [17]:
df.head()

vehicle_name fuel_type    seats    kms_driven  \
0                    2013 Toyota Etios GD    Diesel  5 Seats  1,50,000 Kms   
1                    2024 Toyota Glanza V    Petrol  5 Seats    10,000 Kms   
2           2017 Hyundai Creta 1.4 E Plus    Diesel  5 Seats    75,000 Kms   
3  2011 Volkswagen Vento Diesel Trendline    Diesel  5 Seats  1,60,000 Kms   
4             2014 Hyundai Verna 1.6 CRDI    Diesel  5 Seats  1,20,000 Kms   

     rto_location     ownership engine_displacement transmission_type  \
0  Sri Ganganagar  Fourth Owner             1364 cc            Manual   
1          dasuya   First Owner             1197 cc            Manual   
2         Gurgaon   First Owner             1396 cc            Manual   
3       jalalabad   Third Owner             1598 cc            Manual   
4          Meerut   First Owner             1582 cc            Manual   

  engine_power drive_type          new_vehicle_price  \
0          NaN        NaN   New Car Price ₹8.05 Lakh   
1          NaN        NaN  New Car Price ₹11.28 Lakh   
2          NaN        NaN  New Car Price ₹11.86 Lakh   
3    103.6 bhp        NaN  New Car Price ₹10.05 Lakh   
4    126.3 bhp        NaN  New Car Price ₹11.87 Lakh   

                vehicle_price  \
0                 ₹2.60 Lakh    
1                 ₹9.40 Lakh    
2  ₹6.25 Lakh Make Your Offer   
3                 ₹1.40 Lakh    
4                    ₹4 Lakh    

                                     other_features  mileage(kmpl)  \
0                                                []            NaN   
1                                                []            NaN   
2                                                []            NaN   
3                               ['Parking Sensors']          20.54   
4  ['Automatic Climate Control', 'Parking Sensors']          22.32   

   registration_year       brand   model  
0               2013      Toyota   Etios  
1               2024      Toyota  Glanza  
2               2017     Hyundai   Creta  
3               2011  Volkswagen   Vento  
4               2014     Hyundai   Verna

In [18]:
df.isnull().sum()

vehicle_name              0
fuel_type                 0
seats                    12
kms_driven                0
rto_location            667
ownership                 3
engine_displacement      86
transmission_type         0
engine_power           3126
drive_type             7977
new_vehicle_price         0
vehicle_price             0
other_features            0
mileage(kmpl)          3333
registration_year         0
brand                     0
model                     0
dtype: int64

In [19]:
df['fuel_type'].value_counts()

fuel_type
Petrol      5563
Diesel      4209
CNG          330
Electric      82
LPG           40
Name: count, dtype: int64

In [45]:
df['fuel_type']  = df['fuel_type'].astype('category')

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10224 entries, 0 to 10223
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype   
---  ------             --------------  -----   
 0   vehicle_name       10224 non-null  object  
 1   fuel_type          10224 non-null  category
 2   seats              10224 non-null  object  
 3   kms_driven         10224 non-null  int64   
 4   ownership          10224 non-null  category
 5   engine(cc)         10224 non-null  int32   
 6   transmission_type  10224 non-null  object  
 7   engine_power       7098 non-null   object  
 8   drive_type         2247 non-null   object  
 9   new_vehicle_price  10224 non-null  object  
 10  vehicle_price      10224 non-null  object  
 11  other_features     10224 non-null  object  
 12  mileage(kmpl)      6891 non-null   float64 
 13  registration_year  10224 non-null  int64   
 14  brand              10224 non-null  object  
 15  model              10224 non-null  object  
 16  rto_state

#### Seats :

In [22]:
df.head()

vehicle_name fuel_type    seats    kms_driven  \
0                    2013 Toyota Etios GD    Diesel  5 Seats  1,50,000 Kms   
1                    2024 Toyota Glanza V    Petrol  5 Seats    10,000 Kms   
2           2017 Hyundai Creta 1.4 E Plus    Diesel  5 Seats    75,000 Kms   
3  2011 Volkswagen Vento Diesel Trendline    Diesel  5 Seats  1,60,000 Kms   
4             2014 Hyundai Verna 1.6 CRDI    Diesel  5 Seats  1,20,000 Kms   

     rto_location     ownership engine_displacement transmission_type  \
0  Sri Ganganagar  Fourth Owner             1364 cc            Manual   
1          dasuya   First Owner             1197 cc            Manual   
2         Gurgaon   First Owner             1396 cc            Manual   
3       jalalabad   Third Owner             1598 cc            Manual   
4          Meerut   First Owner             1582 cc            Manual   

  engine_power drive_type          new_vehicle_price  \
0          NaN        NaN   New Car Price ₹8.05 Lakh   
1          NaN        NaN  New Car Price ₹11.28 Lakh   
2          NaN        NaN  New Car Price ₹11.86 Lakh   
3    103.6 bhp        NaN  New Car Price ₹10.05 Lakh   
4    126.3 bhp        NaN  New Car Price ₹11.87 Lakh   

                vehicle_price  \
0                 ₹2.60 Lakh    
1                 ₹9.40 Lakh    
2  ₹6.25 Lakh Make Your Offer   
3                 ₹1.40 Lakh    
4                    ₹4 Lakh    

                                     other_features  mileage(kmpl)  \
0                                                []            NaN   
1                                                []            NaN   
2                                                []            NaN   
3                               ['Parking Sensors']          20.54   
4  ['Automatic Climate Control', 'Parking Sensors']          22.32   

   registration_year       brand   model  
0               2013      Toyota   Etios  
1               2024      Toyota  Glanza  
2               2017     Hyundai   Creta  
3               2011  Volkswagen   Vento  
4               2014     Hyundai   Verna

In [23]:
df['seats'].isnull().sum()

np.int64(12)

In [24]:
temp_df = df[df['seats'].isnull()]

In [48]:
df['seats'].value_counts()

seats
5 Seats     8260
7 Seats     1474
4 Seats      161
6 Seats      155
8 Seats      121
9 Seats       30
2 Seats       12
10 Seats      11
Name: count, dtype: int64

In [49]:
df['seats'] = df['seats'].astype('category')

In [27]:
df.loc[df['vehicle_name'].str.contains("Scorpio", case=False) & df['seats'].isna(), 'seats'] = '7 Seats'
df.loc[df['seats'].isna(), 'seats'] = '5 Seats'

In [28]:
df.loc[temp_df.index,'seats']

830     5 Seats
2066    5 Seats
2341    5 Seats
3936    5 Seats
4305    5 Seats
5124    5 Seats
5820    5 Seats
6437    5 Seats
7317    7 Seats
7529    5 Seats
7769    5 Seats
9813    7 Seats
Name: seats, dtype: category
Categories (8, object): ['10 Seats', '2 Seats', '4 Seats', '5 Seats', '6 Seats', '7 Seats', '8 Seats', '9 Seats']

In [50]:
df.isnull().sum()

vehicle_name            0
fuel_type               0
seats                   0
kms_driven              0
ownership               0
engine(cc)              0
transmission_type       0
engine_power         3126
drive_type           7977
new_vehicle_price       0
vehicle_price           0
other_features          0
mileage(kmpl)        3333
registration_year       0
brand                   0
model                   0
rto_state               0
dtype: int64

#### kms_driven	:

In [30]:
df.head()

vehicle_name fuel_type    seats    kms_driven  \
0                    2013 Toyota Etios GD    Diesel  5 Seats  1,50,000 Kms   
1                    2024 Toyota Glanza V    Petrol  5 Seats    10,000 Kms   
2           2017 Hyundai Creta 1.4 E Plus    Diesel  5 Seats    75,000 Kms   
3  2011 Volkswagen Vento Diesel Trendline    Diesel  5 Seats  1,60,000 Kms   
4             2014 Hyundai Verna 1.6 CRDI    Diesel  5 Seats  1,20,000 Kms   

     rto_location     ownership engine_displacement transmission_type  \
0  Sri Ganganagar  Fourth Owner             1364 cc            Manual   
1          dasuya   First Owner             1197 cc            Manual   
2         Gurgaon   First Owner             1396 cc            Manual   
3       jalalabad   Third Owner             1598 cc            Manual   
4          Meerut   First Owner             1582 cc            Manual   

  engine_power drive_type          new_vehicle_price  \
0          NaN        NaN   New Car Price ₹8.05 Lakh   
1          NaN        NaN  New Car Price ₹11.28 Lakh   
2          NaN        NaN  New Car Price ₹11.86 Lakh   
3    103.6 bhp        NaN  New Car Price ₹10.05 Lakh   
4    126.3 bhp        NaN  New Car Price ₹11.87 Lakh   

                vehicle_price  \
0                 ₹2.60 Lakh    
1                 ₹9.40 Lakh    
2  ₹6.25 Lakh Make Your Offer   
3                 ₹1.40 Lakh    
4                    ₹4 Lakh    

                                     other_features  mileage(kmpl)  \
0                                                []            NaN   
1                                                []            NaN   
2                                                []            NaN   
3                               ['Parking Sensors']          20.54   
4  ['Automatic Climate Control', 'Parking Sensors']          22.32   

   registration_year       brand   model  
0               2013      Toyota   Etios  
1               2024      Toyota  Glanza  
2               2017     Hyundai   Creta  
3               2011  Volkswagen   Vento  
4               2014     Hyundai   Verna

In [31]:
df['kms_driven'].isnull().sum()

np.int64(0)

In [32]:
#cleaning the km_driven col and converting it into numeric
df['kms_driven']  = df['kms_driven'].str.replace(r'Kms|,','',regex=True).astype('int')

In [33]:
df['kms_driven'].dtype

dtype('int64')

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10224 entries, 0 to 10223
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype   
---  ------               --------------  -----   
 0   vehicle_name         10224 non-null  object  
 1   fuel_type            10224 non-null  category
 2   seats                10224 non-null  category
 3   kms_driven           10224 non-null  int64   
 4   rto_location         9557 non-null   object  
 5   ownership            10221 non-null  object  
 6   engine_displacement  10138 non-null  object  
 7   transmission_type    10224 non-null  object  
 8   engine_power         7098 non-null   object  
 9   drive_type           2247 non-null   object  
 10  new_vehicle_price    10224 non-null  object  
 11  vehicle_price        10224 non-null  object  
 12  other_features       10224 non-null  object  
 13  mileage(kmpl)        6891 non-null   float64 
 14  registration_year    10224 non-null  int64   
 15  brand                102

#### rto_location :

In [35]:
df.head()

vehicle_name fuel_type    seats  kms_driven  \
0                    2013 Toyota Etios GD    Diesel  5 Seats      150000   
1                    2024 Toyota Glanza V    Petrol  5 Seats       10000   
2           2017 Hyundai Creta 1.4 E Plus    Diesel  5 Seats       75000   
3  2011 Volkswagen Vento Diesel Trendline    Diesel  5 Seats      160000   
4             2014 Hyundai Verna 1.6 CRDI    Diesel  5 Seats      120000   

     rto_location     ownership engine_displacement transmission_type  \
0  Sri Ganganagar  Fourth Owner             1364 cc            Manual   
1          dasuya   First Owner             1197 cc            Manual   
2         Gurgaon   First Owner             1396 cc            Manual   
3       jalalabad   Third Owner             1598 cc            Manual   
4          Meerut   First Owner             1582 cc            Manual   

  engine_power drive_type          new_vehicle_price  \
0          NaN        NaN   New Car Price ₹8.05 Lakh   
1          NaN        NaN  New Car Price ₹11.28 Lakh   
2          NaN        NaN  New Car Price ₹11.86 Lakh   
3    103.6 bhp        NaN  New Car Price ₹10.05 Lakh   
4    126.3 bhp        NaN  New Car Price ₹11.87 Lakh   

                vehicle_price  \
0                 ₹2.60 Lakh    
1                 ₹9.40 Lakh    
2  ₹6.25 Lakh Make Your Offer   
3                 ₹1.40 Lakh    
4                    ₹4 Lakh    

                                     other_features  mileage(kmpl)  \
0                                                []            NaN   
1                                                []            NaN   
2                                                []            NaN   
3                               ['Parking Sensors']          20.54   
4  ['Automatic Climate Control', 'Parking Sensors']          22.32   

   registration_year       brand   model  
0               2013      Toyota   Etios  
1               2024      Toyota  Glanza  
2               2017     Hyundai   Creta  
3               2011  Volkswagen   Vento  
4               2014     Hyundai   Verna

In [36]:
df['rto_location'].isnull().sum()

np.int64(667)

In [38]:
import pandas as pd
import re
import rapidfuzz
from rapidfuzz import process

# -----------------------------
# NUMBER PLATE PREFIX → STATE
# -----------------------------
plate_state_map = {
    'AP': 'Andhra Pradesh', 'AR': 'Arunachal Pradesh','AS': 'Assam','BR': 'Bihar',
    'CH': 'Chandigarh','CG': 'Chhattisgarh','DD': 'Daman and Diu','DL': 'Delhi','DN': 'Dadra and Nagar Haveli',
    'GA': 'Goa','GJ': 'Gujarat','HP': 'Himachal Pradesh','HR': 'Haryana','JH': 'Jharkhand',
    'JK': 'Jammu & Kashmir','KA': 'Karnataka','KL': 'Kerala','LA': 'Ladakh','LD': 'Lakshadweep',
    'MH': 'Maharashtra','ML': 'Meghalaya','MN': 'Manipur','MP': 'Madhya Pradesh','MZ': 'Mizoram',
    'NL': 'Nagaland','OD': 'Odisha','OR': 'Odisha','PB': 'Punjab','PY': 'Puducherry','RJ': 'Rajasthan',
    'SK': 'Sikkim','TN': 'Tamil Nadu','TR': 'Tripura','TS': 'Telangana','TG': 'Telangana',
    'UP': 'Uttar Pradesh','UK': 'Uttarakhand','UA': 'Uttarakhand','WB': 'West Bengal'
}

# -----------------------------
# COMPLETE INDIA DISTRICT LIST
# -----------------------------
# Clean and official district names
# (Only ~750 names, not 1100, covers ALL India)
from collections import defaultdict

district_to_state = defaultdict(str)

# Load all districts of India (condensed for accuracy)
district_data = {
    "Andhra Pradesh": ["Prakasam","Guntur","Krishna","Kurnool","Kadapa","Chittoor","Anantapur","Srikakulam","Vizianagaram","Visakhapatnam","Nellore","East Godavari","West Godavari"],
    "Telangana": ["Hyderabad","Ranga Reddy","Medak","Karimnagar","Nizamabad","Nalgonda","Adilabad","Khammam","Warangal","Mahbubnagar","Siddipet"],
    "Maharashtra": ["Mumbai","Pune","Thane","Nashik","Nagpur","Solapur","Kolhapur","Satara","Sangli","Wardha","Washim","Amravati","Aurangabad","Beed","Osmanabad","Parbhani","Nanded","Latur","Ratnagiri","Sindhudurg","Palghar","Raigad"],
    "Karnataka": ["Bangalore","Mysore","Mangalore","Udupi","Hubli","Dharwad","Belgaum","Bidar","Raichur","Bellary","Tumkur","Kolar"],
    "Tamil Nadu": ["Chennai","Coimbatore","Madurai","Salem","Trichy","Tirunelveli","Vellore","Erode","Thanjavur","Dharmapuri","Krishnagiri","Villupuram"],
    "Kerala": ["Kochi","Ernakulam","Thiruvananthapuram","Kottayam","Kollam","Thrissur","Malappuram","Palakkad","Kasaragod"],
    "Uttar Pradesh": ["Kanpur","Lucknow","Meerut","Noida","Ghaziabad","Varanasi","Allahabad","Agra","Aligarh","Gonda","Basti","Bareilly"],
    "West Bengal": ["Kolkata","Howrah","Darjeeling","Hooghly","Siliguri","Bardhaman","Birbhum","Murshidabad","South 24 Parganas","Nadia"],
    "Gujarat": ["Ahmedabad","Surat","Vadodara","Rajkot","Bhavnagar","Junagadh","Gandhinagar","Mehsana","Banaskantha","Valsad","Navsari","Porbandar"],
    "Rajasthan": ["Jaipur","Jodhpur","Udaipur","Bikaner","Kota","Alwar","Ajmer","Bharatpur","Barmer","Churu","Jhunjhunu"],
    "Punjab": ["Amritsar","Ludhiana","Jalandhar","Patiala","Bathinda","Firozpur","Mohali","Gurdaspur","Sangrur"],
    "Haryana": ["Gurgaon","Faridabad","Panipat","Karnal","Rohtak","Hisar","Sirsa","Yamuna Nagar","Ambala"],
    "Bihar": ["Patna","Gaya","Bhagalpur","Muzaffarpur","Begusarai","Darbhanga","Ara","Nalanda"],
    "Assam": ["Guwahati","Jorhat","Dibrugarh","Silchar","Sivasagar","Tinsukia","Goalpara","Nagaon"],
    "Odisha": ["Bhubaneswar","Cuttack","Koraput","Sambalpur","Rayagada","Ganjam"],
    "Madhya Pradesh": ["Bhopal","Indore","Ujjain","Gwalior","Jabalpur","Rewa","Sagar","Ratlam"],
    # (Can expand anytime)
}

# Flatten dictionary into district → state
for state, districts in district_data.items():
    for dist in districts:
        district_to_state[dist] = state


# -----------------------------
# DETECT STATE (FINAL FUNCTION)
# -----------------------------
def detect_state_from_plate(value):
    value = str(value).strip().upper()
    match = re.match(r'^([A-Z]{2})\d+', value)
    if match:
        code = match.group(1)
        return plate_state_map.get(code)
    return None

def get_rto_state(value):
    if pd.isna(value) or str(value).strip() == "":
        return "Unknown"

    val = str(value).strip().title()

    # 1. Number plate (AP40, TS07)
    state = detect_state_from_plate(val)
    if state:
        return state

    # 2. City/district fuzzy search
    result = process.extractOne(val, district_to_state.keys())
    if result:
        match, score, _ = result
        if score >= 85:
            return district_to_state[match]

    return "Unknown"



# -----------------------------
# APPLY TO YOUR DATA
# -----------------------------
df['rto_state'] = df['rto_location'].apply(get_rto_state)


In [46]:
df['rto_state'].value_counts()

rto_state
Unknown                   4777
Maharashtra                932
Uttar Pradesh              572
Gujarat                    530
Haryana                    436
Rajasthan                  379
Madhya Pradesh             360
Telangana                  353
Karnataka                  315
West Bengal                312
Andhra Pradesh             276
Tamil Nadu                 251
Punjab                     189
Assam                      181
Bihar                      137
Odisha                     123
Kerala                      85
Daman and Diu                8
Dadra and Nagar Haveli       2
Tripura                      1
Chandigarh                   1
Arunachal Pradesh            1
Sikkim                       1
Himachal Pradesh             1
Meghalaya                    1
Name: count, dtype: int64

In [57]:
rto_state_mapping = {
    # Union Territories
    'New Delhi': 'Delhi', 'Chandigarh': 'Chandigarh', 'Daman': 'Daman and Diu',
    'Silvassa': 'Dadra and Nagar Haveli and Daman and Diu', 'Panaji': 'Goa',
    'Margao': 'Goa', 'Vasco Da Gama': 'Goa', 'mapusa': 'Goa', 'ponda': 'Goa',
    'Canacona': 'Goa', 'Diu': 'Daman and Diu', 'Port Blair': 'Andaman and Nicobar Islands',
    'Pondicherry': 'Puducherry',
    
    # Andhra Pradesh (AP)
    'Vijayawada': 'Andhra Pradesh', 'eluru': 'Andhra Pradesh', 'Rajahmundry': 'Andhra Pradesh',
    'ongole': 'Andhra Pradesh', 'Tirupati': 'Andhra Pradesh', 'kakinada': 'Andhra Pradesh',
    'Gajuwaka': 'Andhra Pradesh',
    
    # Arunachal Pradesh (AR)
    'Itanagar': 'Arunachal Pradesh', 'Lohit': 'Arunachal Pradesh', 'Pasighat': 'Arunachal Pradesh',
    'Dibang Valley': 'Arunachal Pradesh', 'Bomdila': 'Arunachal Pradesh',
    
    # Assam (AS)
    'Cachar': 'Assam', 'Karimganj': 'Assam', 'Hailakandi': 'Assam', 'Dhubri': 'Assam',
    'Sonitpur': 'Assam', 'Golaghat': 'Assam', 'Darrang': 'Assam', 'Udalguri': 'Assam',
    'Nalbari': 'Assam', 'barpeta': 'Assam', 'Bongaigaon': 'Assam', 'Kokrajhar': 'Assam',
    'Dhemaji': 'Assam', 'Karbi Anglong': 'Assam',

    # Bihar (BR)
    'motihari': 'Bihar', 'Nawada': 'Bihar', 'Bhabua': 'Bihar', 'Vaishali': 'Bihar',
    'Samastipur': 'Bihar', 'Khagaria': 'Bihar', 'Bhojpur': 'Bihar', 'Chhapra': 'Bihar',
    'Sitamarhi': 'Bihar', 'Madhepura': 'Bihar', 'Bettiah': 'Bihar', 'siwan': 'Bihar',
    'Saharsa': 'Bihar', 'Sheohar': 'Bihar', 'Gopalganj': 'Bihar',

    # Chhattisgarh (CG)
    'Durg': 'Chhattisgarh', 'Raipur': 'Chhattisgarh', 'Dhamtari': 'Chhattisgarh',
    'Bemetara': 'Chhattisgarh', 'Janjgir-Champa': 'Chhattisgarh', 'rajnandgaon': 'Chhattisgarh',
    'Baloda Bazar': 'Chhattisgarh', 'Gariaband': 'Chhattisgarh', 'Mahasamund': 'Chhattisgarh',
    'Bilaspur': 'Chhattisgarh', 'Kawardha': 'Chhattisgarh', 'Jagdalpur': 'Chhattisgarh',
    'Dantewada': 'Chhattisgarh', 'Kanker': 'Chhattisgarh', 'Bijapur': 'Chhattisgarh',
    'raigarh': 'Chhattisgarh', 'ambikapur': 'Chhattisgarh', 'Koriya': 'Chhattisgarh',
    'Korba': 'Chhattisgarh',

    # Gujarat (GJ)
    'Bharuch': 'Gujarat', 'Narmada': 'Gujarat', 'Gandhidham': 'Gujarat', 'Jalore': 'Gujarat',
    'patan': 'Gujarat', 'Sabarkantha': 'Gujarat', 'Kheda': 'Gujarat', 'Surendranagar': 'Gujarat',
    'Anand': 'Gujarat', 'bardoli': 'Gujarat', 'Morbi': 'Gujarat', 'Mandvi (Kachchh)': 'Gujarat',
    'Godhra': 'Gujarat', 'Veraval': 'Gujarat', 'amreli': 'Gujarat', 'dahod': 'Gujarat',

    # Haryana (HR)
    'Kaithal': 'Haryana', 'palwal': 'Haryana', 'Fatehabad': 'Haryana', 'Sonipat': 'Haryana',
    'charkhi dadri': 'Haryana', 'Bhiwani': 'Haryana', 'Safidon': 'Haryana', 'Narnaud': 'Haryana',
    'Jind': 'Haryana', 'gohana': 'Haryana', 'hansi': 'Haryana', 'Sohna': 'Haryana',
    'bahadurgarh': 'Haryana', 'samalkha': 'Haryana', 'Jagadhri': 'Haryana', 'Mahendragarh': 'Haryana',
    'naraingarh': 'Haryana', 'Pehowa': 'Haryana', 'Radaur': 'Haryana', 'Meham': 'Haryana',
    'pataudi': 'Haryana',

    # Himachal Pradesh (HP)
    'Shimla': 'Himachal Pradesh', 'Kangra': 'Himachal Pradesh', 'Dharamshala': 'Himachal Pradesh',
    'Palampur': 'Himachal Pradesh', 'Hamirpur(hp)': 'Himachal Pradesh', 'Solan': 'Himachal Pradesh',
    'Mandi': 'Himachal Pradesh', 'Nahan': 'Himachal Pradesh', 'Bilaspur': 'Himachal Pradesh',
    'Rampur Bushahr': 'Himachal Pradesh', 'Kinnaur': 'Himachal Pradesh', 'Barsar': 'Himachal Pradesh',
    'dehra gopipur': 'Himachal Pradesh', 'kalka': 'Himachal Pradesh', 'kullu': 'Himachal Pradesh',

    # Jammu and Kashmir (JK) / Ladakh (LA) - Mapping to their regions
    'Jammu': 'Jammu and Kashmir', 'Srinagar': 'Jammu and Kashmir', 'Baramulla': 'Jammu and Kashmir',
    'Anantnag': 'Jammu and Kashmir', 'Kulgam': 'Jammu and Kashmir', 'Poonch': 'Jammu and Kashmir',
    'Udhampur': 'Jammu and Kashmir', 'Rajauri': 'Jammu and Kashmir', 'Ganderbal': 'Jammu and Kashmir',
    'Bandipore': 'Jammu and Kashmir', 'pulwama': 'Jammu and Kashmir', 'kupwara': 'Jammu and Kashmir',
    'Budgam': 'Jammu and Kashmir', 'Leh': 'Ladakh',
    
    # Jharkhand (JH)
    'Ranchi': 'Jharkhand', 'Jamshedpur': 'Jharkhand', 'Dhanbad': 'Jharkhand', 'Bokaro': 'Jharkhand',
    'Giridih': 'Jharkhand', 'Hazaribagh': 'Jharkhand', 'Koderma': 'Jharkhand', 'Medininagar': 'Jharkhand',
    'lohardaga': 'Jharkhand', 'ramgarh': 'Jharkhand', 'Sahibganj': 'Jharkhand', 'Purulia': 'Jharkhand', # Purulia is in WB, but sometimes listed in JH data.
    'Seraikela-kharsawan': 'Jharkhand',

    # Karnataka (KA)
    'Yadgir': 'Karnataka', 'Hospet': 'Karnataka', 'Chikkaballapur': 'Karnataka', 'Chitradurga': 'Karnataka',
    'Gulbarga': 'Karnataka', 'Hassan': 'Karnataka', 'Shimoga': 'Karnataka', 'Davangere': 'Karnataka',
    'Chikmagalur': 'Karnataka', 'Muvattupuzha': 'Karnataka', # Muvattupuzha is in Kerala, but RTO could be regional. Keeping in mind the data format.
    'Madikeri': 'Karnataka', 'Uttara Kannada': 'Karnataka', 'Sirsi': 'Karnataka', 'Chikodi': 'Karnataka',
    'Haveri': 'Karnataka', 'Ranebennuru': 'Karnataka', 'Gadag': 'Karnataka', 'Gokak': 'Karnataka',
    'karwar': 'Karnataka', 'Jamakhandi': 'Karnataka', 'Bagalkot': 'Karnataka', 'Koppal': 'Karnataka',
    'ramanagara': 'Karnataka', 'puttur': 'Karnataka', 'tiptur': 'Karnataka',

    # Kerala (KL)
    'Chengannur': 'Kerala', 'Thalassery': 'Kerala', 'aluva': 'Kerala', 'thodupuzha': 'Kerala',
    'Alappuzha': 'Kerala', 'Kayamkulam': 'Kerala', 'ranni': 'Kerala', 'Mallappally': 'Kerala',
    'mavelikara': 'Kerala', 'Kottarakkara': 'Kerala', 'irinjalakuda': 'Kerala', 'Karunagappally': 'Kerala',
    'Nedumangad': 'Kerala', 'attingal': 'Kerala', 'punalur': 'Kerala', 'changanassery': 'Kerala',
    'Payyanur': 'Kerala', 'Neyyattinkara': 'Kerala', 'taliparamba': 'Kerala', 'Sultan Bathery': 'Kerala',
    'Pathanamthitta': 'Kerala', 'Idukki': 'Kerala', 'Kanjirappally': 'Kerala', 'Kattakkada': 'Kerala',
    'pattambi': 'Kerala', 'Mannarkkad': 'Kerala', 'Guruvayoor': 'Kerala', 'wadakkanchery': 'Kerala',
    'Kothamangalam': 'Kerala', 'Chalakudy': 'Kerala', 'Varkala': 'Kerala', 'Koyilandy': 'Kerala',
    'Tirur': 'Kerala', 'Perinthalmanna': 'Kerala', 'Kozhikode': 'Kerala', 'Kannur': 'Kerala',

    # Madhya Pradesh (MP)
    'Agar Malwa': 'Madhya Pradesh', 'Neemuch': 'Madhya Pradesh', 'Barwani': 'Madhya Pradesh',
    'Katni': 'Madhya Pradesh', 'Panna': 'Madhya Pradesh', 'Vidisha': 'Madhya Pradesh',
    'Betul': 'Madhya Pradesh', 'Khargone': 'Madhya Pradesh', 'Khandwa': 'Madhya Pradesh',
    'burhanpur': 'Madhya Pradesh', 'Dindori': 'Madhya Pradesh', 'Dewas': 'Madhya Pradesh',
    'Sehore': 'Madhya Pradesh', 'Sheopur': 'Madhya Pradesh', 'Shivpuri': 'Madhya Pradesh',
    'Guna': 'Madhya Pradesh', 'Morena': 'Madhya Pradesh', 'Lalitpur': 'Madhya Pradesh', # Lalitpur is UP, checking data
    'Raisen': 'Madhya Pradesh', 'Rajgarh': 'Madhya Pradesh', 'Umaria': 'Madhya Pradesh',
    'Chhindwara': 'Madhya Pradesh', 'Shahdol': 'Madhya Pradesh', 'Anuppur': 'Madhya Pradesh',
    'Narsinghpur': 'Madhya Pradesh', 'Singrauli': 'Madhya Pradesh', 'Sidhi': 'Madhya Pradesh',
    'chattarpur': 'Madhya Pradesh', 'mahoba': 'Madhya Pradesh', 'Tikamgarh': 'Madhya Pradesh',

    # Maharashtra (MH)
    'Yavatmal': 'Maharashtra', 'bhandara': 'Maharashtra', 'Pimpri chinchwad': 'Maharashtra',
    'kalyan': 'Maharashtra', 'panvel': 'Maharashtra', 'karad': 'Maharashtra', 'Chandrapur': 'Maharashtra',
    'Hingoli': 'Maharashtra', 'Ahmednagar': 'Maharashtra', 'shrirampur': 'Maharashtra', 'Akola': 'Maharashtra',
    'Jalgaon': 'Maharashtra', 'Dhule': 'Maharashtra', 'nandurbar': 'Maharashtra', 'Buldhana': 'Maharashtra',
    'Ambajogai': 'Maharashtra', 'akluj': 'Maharashtra', 'jalna': 'Maharashtra', 'vasai': 'Maharashtra',
    'baramati': 'Maharashtra', 'malegaon': 'Maharashtra', 'Urun Islampur': 'Maharashtra',

    # Meghalaya (ML)
    'East Khasi Hills': 'Meghalaya', 'Jaintia Hills': 'Meghalaya', 'khliehriat': 'Meghalaya',
    'Nongpoh': 'Meghalaya', 'West Garo Hills': 'Meghalaya',

    # Mizoram (MZ)
    'Aizawl': 'Mizoram', 'Champhai': 'Mizoram', 'Lunglei': 'Mizoram',

    # Nagaland (NL)
    'Dimapur': 'Nagaland', 'Kohima': 'Nagaland', 'Tuensang': 'Nagaland',

    # Odisha (OD)
    'Mayurbhanj': 'Odisha', 'Balasore': 'Odisha', 'Jharsuguda': 'Odisha', 'Sundergarh': 'Odisha',
    'Rourkela': 'Odisha', 'Angul': 'Odisha', 'Bhanjanagar': 'Odisha', 'Puri': 'Odisha',
    'jajpur': 'Odisha', 'Balangir': 'Odisha', 'Bargarh': 'Odisha', 'Phulbani': 'Odisha',
    'Boudh': 'Odisha', 'Kalahandi': 'Odisha', 'Nabarangpur': 'Odisha', 'Malkangiri': 'Odisha',
    'Kendujhar': 'Odisha',

    # Punjab (PB)
    'dasuya': 'Punjab', 'jalalabad': 'Punjab', 'malout': 'Punjab', 'Moga': 'Punjab',
    'barnala': 'Punjab', 'jagraon': 'Punjab', 'Mansa': 'Punjab', 'zira': 'Punjab',
    'Abohar': 'Punjab', 'Sri Muktsar Sahib': 'Punjab', 'kharar': 'Punjab', 'Khanna': 'Punjab',
    'phagwara': 'Punjab', 'Una': 'Punjab', # Una is in HP, but RTO could be regional. Keeping in mind the data format.
    'Kapurthala': 'Punjab', 'Rupnagar': 'Punjab', 'Batala': 'Punjab', 'Jaitu': 'Punjab',
    'Tarn Taran': 'Punjab', 'Anandpur Sahib': 'Punjab', 'Fatehgarh': 'Punjab', 'patran': 'Punjab',
    'Phillaur': 'Punjab', 'Faridkot': 'Punjab', 'rajpura': 'Punjab',

    # Rajasthan (RJ)
    'Sri Ganganagar': 'Rajasthan', 'Hanumangarh': 'Rajasthan', 'Rawatbhata': 'Rajasthan',
    'Banswara': 'Rajasthan', 'Pali': 'Rajasthan', 'Jalore': 'Rajasthan', 'sirohi': 'Rajasthan',
    'rajsamand': 'Rajasthan', 'Chittorgarh': 'Rajasthan', 'Bhilwara': 'Rajasthan', 'Bundi': 'Rajasthan',
    'Ramganj Mandi': 'Rajasthan', 'Nagaur': 'Rajasthan', 'didwana': 'Rajasthan', 'Nohar': 'Rajasthan',
    'Jaisalmer': 'Rajasthan', 'dausa': 'Rajasthan', 'balotra': 'Rajasthan', 'Sikar': 'Rajasthan',
    'kotputli': 'Rajasthan', 'Kishangarh': 'Rajasthan', 'Phalodi': 'Rajasthan', 'shahpura': 'Rajasthan',
    'sawai madhopur': 'Rajasthan', 'tonk': 'Rajasthan', 'dungarpur': 'Rajasthan', 'baran': 'Rajasthan',
    'jhalawar': 'Rajasthan', 'beawar': 'Rajasthan',

    # Sikkim (SK)
    'Gangtok': 'Sikkim',

    # Tamil Nadu (TN)
    'Nagercoil': 'Tamil Nadu', 'Thoothukudi': 'Tamil Nadu', 'Tiruppur': 'Tamil Nadu', 'Tenkasi': 'Tamil Nadu',
    'Kovilpatti': 'Tamil Nadu', 'Sivakasi': 'Tamil Nadu', 'Chengalpattu': 'Tamil Nadu', 'Poonamallee': 'Tamil Nadu',
    'red hills': 'Tamil Nadu', 'Tindivanam': 'Tamil Nadu', 'Nagapattinam': 'Tamil Nadu', 'thiruvarur': 'Tamil Nadu',
    'Tiruchirappalli': 'Tamil Nadu', 'Attur': 'Tamil Nadu', 'Kanchipuram': 'Tamil Nadu', 'Ranipet': 'Tamil Nadu',
    'Tiruvallur': 'Tamil Nadu', 'Tiruvannamalai': 'Tamil Nadu', 'Ramanathapuram': 'Tamil Nadu',
    'Perambalur': 'Tamil Nadu', 'Cuddalore': 'Tamil Nadu', 'Srirangam': 'Tamil Nadu', 'Gudalur': 'Tamil Nadu',
    'Periyakulam': 'Tamil Nadu', 'Dindigul': 'Tamil Nadu', 'Melur': 'Tamil Nadu', 'Sulur': 'Tamil Nadu',
    'pollachi': 'Tamil Nadu', 'Udumalaipettai': 'Tamil Nadu', 'Virudhunagar': 'Tamil Nadu', 'Sivaganga': 'Tamil Nadu',
    'hosur': 'Tamil Nadu', 'Marthandam': 'Tamil Nadu', 'Tiruchengode': 'Tamil Nadu', 'Namakkal': 'Tamil Nadu',
    'mettupalayam': 'Tamil Nadu',

    # Telangana (TS)
    'nirmal': 'Telangana', 'Secunderabad': 'Telangana', 'Sangareddi': 'Telangana', 'mancherial': 'Telangana',
    'Wanaparthy': 'Telangana', 'Vikarabad': 'Telangana', 'Suryapet': 'Telangana', 'Bhuvanagiri': 'Telangana',
    'Kamareddy': 'Telangana', 'Peddapalli': 'Telangana', 'jagtial': 'Telangana', 'kothagudem': 'Telangana',

    # Tripura (TR)
    'Agartala': 'Tripura', 'South Tripura': 'Tripura', 'dharmanagar': 'Tripura',

    # Uttar Pradesh (UP)
    'banda': 'Uttar Pradesh', 'Etah': 'Uttar Pradesh', 'Balrampur': 'Uttar Pradesh', 'Deoria': 'Uttar Pradesh',
    'Firozabad': 'Uttar Pradesh', 'Barabanki': 'Uttar Pradesh', 'mainpuri': 'Uttar Pradesh',
    'Ambedkar Nagar': 'Uttar Pradesh', 'Mathura': 'Uttar Pradesh', 'bulandshahr': 'Uttar Pradesh',
    'Sonbhadra': 'Uttar Pradesh', 'Saharanpur (UP)': 'Uttar Pradesh', 'Moradabad': 'Uttar Pradesh',
    'budaun': 'Uttar Pradesh', 'hathras': 'Uttar Pradesh', 'Lakhimpur Kheri': 'Uttar Pradesh',
    'Chitrakoot': 'Uttar Pradesh', 'Fatehpur': 'Uttar Pradesh', 'Hamirpur(UP)': 'Uttar Pradesh',
    'Kannauj': 'Uttar Pradesh', 'Pratapgarh': 'Uttar Pradesh', 'Chandauli': 'Uttar Pradesh',
    'Gorakhpur': 'Uttar Pradesh', 'Kaushambi': 'Uttar Pradesh', 'Raebareli': 'Uttar Pradesh',
    'rampur': 'Uttar Pradesh', 'Almora': 'Uttar Pradesh', 'Ghazipur': 'Uttar Pradesh',
    'Jalaun': 'Uttar Pradesh', 'sultanpur': 'Uttar Pradesh', 'Azamgarh': 'Uttar Pradesh',
    'Bhadohi': 'Uttar Pradesh', 'jaunpur': 'Uttar Pradesh', 'Padrauna': 'Uttar Pradesh',
    'Siddharthnagar': 'Uttar Pradesh', 'unnao': 'Uttar Pradesh', 'Auraiya': 'Uttar Pradesh',
    'Farrukhabad': 'Uttar Pradesh', 'Jhansi': 'Uttar Pradesh', 'Mirzapur': 'Uttar Pradesh',
    'Shamli': 'Uttar Pradesh', 'Pilibhit': 'Uttar Pradesh', 'Amroha': 'Uttar Pradesh',
    'Sambhal': 'Uttar Pradesh',

    # Uttarakhand (UK)
    'Nainital': 'Uttarakhand', 'Kashipur': 'Uttarakhand', 'Dehradun': 'Uttarakhand', 'Haridwar': 'Uttarakhand',
    'Udham Singh Nagar': 'Uttarakhand', 'Champawat': 'Uttarakhand', 'Pithoragarh': 'Uttarakhand',
    'Roorkee': 'Uttarakhand', 'Kotdwara': 'Uttarakhand', 'Pauri': 'Uttarakhand', 'Rishikesh': 'Uttarakhand',
    'Tehri': 'Uttarakhand', 'Uttarkashi': 'Uttarakhand', 'Chamoli': 'Uttarakhand',

    # West Bengal (WB)
    'Barasat': 'West Bengal', 'barrackpore': 'West Bengal', 'Asansol': 'West Bengal', 'Durgapur': 'West Bengal',
    'Paschim Medinipur': 'West Bengal', 'Tamluk': 'West Bengal', 'bankura': 'West Bengal',
    'Alipore': 'West Bengal', 'Cooch Behar': 'West Bengal', 'kalimpong': 'West Bengal', 'Rampurhat': 'West Bengal',
    'Maldah': 'West Bengal', 'Jalpaiguri': 'West Bengal', 'Diamond Harbour': 'West Bengal',

    # Special/Unknown Codes (Assigning 'Unknown' or 'Other' to codes or places not easily found or with inconsistent entries)
    'NaN': np.nan, '240B': 'Other/Regional Code', '269': 'Other/Regional Code', 'MA14': 'Other/Regional Code',
    'HM46': 'Other/Regional Code', '220B': 'Other/Regional Code', '230B': 'Other/Regional Code', 'RH02': 'Other/Regional Code',
    'NH30': 'Other/Regional Code', 'AA39': 'Other/Regional Code', 'WW16': 'Other/Regional Code', 'UU12': 'Other/Regional Code',
    'KK08': 'Other/Regional Code', 'BB06': 'Other/Regional Code', 'GG37': 'Other/Regional Code', 'GG10': 'Other/Regional Code',
    'TH43': 'Other/Regional Code', '250B': 'Other/Regional Code', 'PP02': 'Other/Regional Code', 'HA51': 'Other/Regional Code',
    'GH08': 'Other/Regional Code', 'HO30': 'Other/Regional Code', 'MO04': 'Other/Regional Code', 'BA08': 'Other/Regional Code',
    'NP17': 'Other/Regional Code', 'HH12': 'Other/Regional Code', 'CA22': 'Other/Regional Code', 'PP13': 'Other/Regional Code',
    'BT02': 'Other/Regional Code', 'JG15': 'Other/Regional Code', 'GH26': 'Other/Regional Code', 'GH15': 'Other/Regional Code',
    'GH12': 'Other/Regional Code', 'TT28': 'Other/Regional Code', 'BB01': 'Other/Regional Code', 'MM26': 'Other/Regional Code',
    'MM08': 'Other/Regional Code', 'BB29': 'Other/Regional Code', 'KK36': 'Other/Regional Code'
}

In [60]:
df['rto_location'] = df['rto_location'].map(rto_state_mapping)

In [65]:
temp_df = df[df['rto_state']=='Unknown']

In [66]:
df.loc[temp_df.index,'rto_state'] = df.loc[temp_df.index,'rto_location']

In [71]:
df['rto_state'].isnull().sum()

np.int64(1097)

In [73]:
#dropping the rto_location col
df.drop(columns=['rto_location'],axis=1,inplace=True)

In [74]:
df.head()

vehicle_name fuel_type    seats  kms_driven  \
0                    2013 Toyota Etios GD    Diesel  5 Seats      150000   
1                    2024 Toyota Glanza V    Petrol  5 Seats       10000   
2           2017 Hyundai Creta 1.4 E Plus    Diesel  5 Seats       75000   
3  2011 Volkswagen Vento Diesel Trendline    Diesel  5 Seats      160000   
4             2014 Hyundai Verna 1.6 CRDI    Diesel  5 Seats      120000   

      ownership engine_displacement transmission_type engine_power drive_type  \
0  Fourth Owner             1364 cc            Manual          NaN        NaN   
1   First Owner             1197 cc            Manual          NaN        NaN   
2   First Owner             1396 cc            Manual          NaN        NaN   
3   Third Owner             1598 cc            Manual    103.6 bhp        NaN   
4   First Owner             1582 cc            Manual    126.3 bhp        NaN   

           new_vehicle_price               vehicle_price  \
0   New Car Price ₹8.05 Lakh                 ₹2.60 Lakh    
1  New Car Price ₹11.28 Lakh                 ₹9.40 Lakh    
2  New Car Price ₹11.86 Lakh  ₹6.25 Lakh Make Your Offer   
3  New Car Price ₹10.05 Lakh                 ₹1.40 Lakh    
4  New Car Price ₹11.87 Lakh                    ₹4 Lakh    

                                     other_features  mileage(kmpl)  \
0                                                []            NaN   
1                                                []            NaN   
2                                                []            NaN   
3                               ['Parking Sensors']          20.54   
4  ['Automatic Climate Control', 'Parking Sensors']          22.32   

   registration_year       brand   model      rto_state  
0               2013      Toyota   Etios      Rajasthan  
1               2024      Toyota  Glanza         Punjab  
2               2017     Hyundai   Creta        Haryana  
3               2011  Volkswagen   Vento         Punjab  
4               2014     Hyundai   Verna  Uttar Pradesh

In [75]:
# filling the missing values with 'Unknown'
df['rto_state'] = df['rto_state'].fillna('Unknown')

In [76]:
df.isnull().sum()

vehicle_name              0
fuel_type                 0
seats                     0
kms_driven                0
ownership                 3
engine_displacement      86
transmission_type         0
engine_power           3126
drive_type             7977
new_vehicle_price         0
vehicle_price             0
other_features            0
mileage(kmpl)          3333
registration_year         0
brand                     0
model                     0
rto_state                 0
dtype: int64

In [77]:
df['rto_state'] = df['rto_state'].astype('category')

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10224 entries, 0 to 10223
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype   
---  ------               --------------  -----   
 0   vehicle_name         10224 non-null  object  
 1   fuel_type            10224 non-null  category
 2   seats                10224 non-null  category
 3   kms_driven           10224 non-null  int64   
 4   ownership            10221 non-null  object  
 5   engine_displacement  10138 non-null  object  
 6   transmission_type    10224 non-null  object  
 7   engine_power         7098 non-null   object  
 8   drive_type           2247 non-null   object  
 9   new_vehicle_price    10224 non-null  object  
 10  vehicle_price        10224 non-null  object  
 11  other_features       10224 non-null  object  
 12  mileage(kmpl)        6891 non-null   float64 
 13  registration_year    10224 non-null  int64   
 14  brand                10224 non-null  object  
 15  model                102

#### Ownership :

In [83]:
df.head()

vehicle_name fuel_type    seats  kms_driven  \
0                    2013 Toyota Etios GD    Diesel  5 Seats      150000   
1                    2024 Toyota Glanza V    Petrol  5 Seats       10000   
2           2017 Hyundai Creta 1.4 E Plus    Diesel  5 Seats       75000   
3  2011 Volkswagen Vento Diesel Trendline    Diesel  5 Seats      160000   
4             2014 Hyundai Verna 1.6 CRDI    Diesel  5 Seats      120000   

      ownership engine_displacement transmission_type engine_power drive_type  \
0  Fourth Owner             1364 cc            Manual          NaN        NaN   
1   First Owner             1197 cc            Manual          NaN        NaN   
2   First Owner             1396 cc            Manual          NaN        NaN   
3   Third Owner             1598 cc            Manual    103.6 bhp        NaN   
4   First Owner             1582 cc            Manual    126.3 bhp        NaN   

           new_vehicle_price               vehicle_price  \
0   New Car Price ₹8.05 Lakh                 ₹2.60 Lakh    
1  New Car Price ₹11.28 Lakh                 ₹9.40 Lakh    
2  New Car Price ₹11.86 Lakh  ₹6.25 Lakh Make Your Offer   
3  New Car Price ₹10.05 Lakh                 ₹1.40 Lakh    
4  New Car Price ₹11.87 Lakh                    ₹4 Lakh    

                                     other_features  mileage(kmpl)  \
0                                                []            NaN   
1                                                []            NaN   
2                                                []            NaN   
3                               ['Parking Sensors']          20.54   
4  ['Automatic Climate Control', 'Parking Sensors']          22.32   

   registration_year       brand   model      rto_state  
0               2013      Toyota   Etios      Rajasthan  
1               2024      Toyota  Glanza         Punjab  
2               2017     Hyundai   Creta        Haryana  
3               2011  Volkswagen   Vento         Punjab  
4               2014     Hyundai   Verna  Uttar Pradesh

In [84]:
df.isnull().sum()

vehicle_name              0
fuel_type                 0
seats                     0
kms_driven                0
ownership                 3
engine_displacement      86
transmission_type         0
engine_power           3126
drive_type             7977
new_vehicle_price         0
vehicle_price             0
other_features            0
mileage(kmpl)          3333
registration_year         0
brand                     0
model                     0
rto_state                 0
dtype: int64

In [85]:
df['ownership'].value_counts()

ownership
First Owner     6595
Second Owner    2507
Third Owner      783
Fourth Owner     225
Fifth Owner      111
Name: count, dtype: int64

In [86]:
#converting the dtype to category
df['ownership'] = df['ownership'].astype('category')

In [87]:
df[df['ownership'].isnull()]

vehicle_name fuel_type    seats  kms_driven  \
1346    2024 Volkswagen Taigun 1.0 Topline AT    Petrol  5 Seats       15000   
1932  2025 Mahindra XUV700 AX7 Diesel AT BSVI    Diesel  7 Seats         491   
5164                2024 Audi Q3 Bold Edition    Petrol  5 Seats        6691   

     ownership engine_displacement transmission_type engine_power drive_type  \
1346       NaN              999 cc         Automatic   113.98 bhp        FWD   
1932       NaN             2198 cc         Automatic          NaN        NaN   
5164       NaN             1984 cc         Automatic   187.74 bhp        AWD   

              new_vehicle_price                vehicle_price  \
1346  New Car Price ₹20.62 Lakh  ₹17.25 Lakh Make Your Offer   
1932  New Car Price ₹27.24 Lakh     ₹25 Lakh Make Your Offer   
5164  New Car Price ₹65.87 Lakh  ₹44.50 Lakh Make Your Offer   

                                         other_features  mileage(kmpl)  \
1346  ['Ventilated Seats', 'Height Adjustable Driver...          17.23   
1932                                                 []            NaN   
5164  ['Powered Front Seats', 'Height Adjustable Dri...           5.40   

      registration_year       brand   model rto_state  
1346               2024  Volkswagen  Taigun   Unknown  
1932               2025    Mahindra  XUV700   Unknown  
5164               2024        Audi      Q3   Unknown

In [88]:
# filling the missing values with mode
df['ownership'] = df['ownership'].fillna(df['ownership'].mode()[0])

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10224 entries, 0 to 10223
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype   
---  ------               --------------  -----   
 0   vehicle_name         10224 non-null  object  
 1   fuel_type            10224 non-null  object  
 2   seats                10224 non-null  object  
 3   kms_driven           10224 non-null  int64   
 4   ownership            10224 non-null  category
 5   engine_displacement  10138 non-null  object  
 6   transmission_type    10224 non-null  object  
 7   engine_power         7098 non-null   object  
 8   drive_type           2247 non-null   object  
 9   new_vehicle_price    10224 non-null  object  
 10  vehicle_price        10224 non-null  object  
 11  other_features       10224 non-null  object  
 12  mileage(kmpl)        6891 non-null   float64 
 13  registration_year    10224 non-null  int64   
 14  brand                10224 non-null  object  
 15  model                102

#### Engine_displacement :

In [90]:
df.head()

vehicle_name fuel_type    seats  kms_driven  \
0                    2013 Toyota Etios GD    Diesel  5 Seats      150000   
1                    2024 Toyota Glanza V    Petrol  5 Seats       10000   
2           2017 Hyundai Creta 1.4 E Plus    Diesel  5 Seats       75000   
3  2011 Volkswagen Vento Diesel Trendline    Diesel  5 Seats      160000   
4             2014 Hyundai Verna 1.6 CRDI    Diesel  5 Seats      120000   

      ownership engine_displacement transmission_type engine_power drive_type  \
0  Fourth Owner             1364 cc            Manual          NaN        NaN   
1   First Owner             1197 cc            Manual          NaN        NaN   
2   First Owner             1396 cc            Manual          NaN        NaN   
3   Third Owner             1598 cc            Manual    103.6 bhp        NaN   
4   First Owner             1582 cc            Manual    126.3 bhp        NaN   

           new_vehicle_price               vehicle_price  \
0   New Car Price ₹8.05 Lakh                 ₹2.60 Lakh    
1  New Car Price ₹11.28 Lakh                 ₹9.40 Lakh    
2  New Car Price ₹11.86 Lakh  ₹6.25 Lakh Make Your Offer   
3  New Car Price ₹10.05 Lakh                 ₹1.40 Lakh    
4  New Car Price ₹11.87 Lakh                    ₹4 Lakh    

                                     other_features  mileage(kmpl)  \
0                                                []            NaN   
1                                                []            NaN   
2                                                []            NaN   
3                               ['Parking Sensors']          20.54   
4  ['Automatic Climate Control', 'Parking Sensors']          22.32   

   registration_year       brand   model      rto_state  
0               2013      Toyota   Etios      Rajasthan  
1               2024      Toyota  Glanza         Punjab  
2               2017     Hyundai   Creta        Haryana  
3               2011  Volkswagen   Vento         Punjab  
4               2014     Hyundai   Verna  Uttar Pradesh

In [91]:
df.isnull().sum()

vehicle_name              0
fuel_type                 0
seats                     0
kms_driven                0
ownership                 0
engine_displacement      86
transmission_type         0
engine_power           3126
drive_type             7977
new_vehicle_price         0
vehicle_price             0
other_features            0
mileage(kmpl)          3333
registration_year         0
brand                     0
model                     0
rto_state                 0
dtype: int64

In [92]:
df['engine_displacement'] = df['engine_displacement'].str.replace('cc','')

In [93]:
df['engine_displacement'] = df['engine_displacement'].astype('Int32')

In [94]:
df[df['engine_displacement'].isnull()]

vehicle_name fuel_type    seats  \
418              2024 Tata Curvv EV Accomplished 45  Electric  5 Seats   
452                    2024 Tata Punch EV Adventure  Electric  5 Seats   
565                      2022 Tata Tigor EV XZ Plus  Electric  5 Seats   
622                      2024 MG Comet EV Executive  Electric  4 Seats   
655                 2024 Tata Punch EV Adventure LR  Electric  5 Seats   
697         2022 Tata Nexon EV XZ Plus Dark Edition  Electric  5 Seats   
713                      2023 Tata Nexon EV XZ Plus  Electric  5 Seats   
721                        2024 Tata Tiago EV XT LR  Electric  5 Seats   
739                         2021 MG ZS EV Exclusive  Electric  5 Seats   
1107            2024 Hyundai IONIQ 5 Long Range RWD  Electric  5 Seats   
1178                     2024 MG Comet EV Executive  Electric  4 Seats   
1614                    2023 MG ZS EV Exclusive Pro  Electric  5 Seats   
1766                       2023 Tata Tiago EV XT LR  Electric  5 Seats   
1836                        2024 MG ZS EV Executive  Electric  5 Seats   
1888                          2022 Tata Nexon EV XM  Electric  5 Seats   
1908         2024 Tata Curvv EV Empowered Plus A 55  Electric  5 Seats   
2443                           2024 BYD E6 Electric  Electric  5 Seats   
2540        2024 Mahindra XUV400 EV EL Fast Charger  Electric  5 Seats   
2577                2024 Tata Punch EV Adventure LR  Electric  5 Seats   
2677                    2025 Mahindra BE 6 Pack One  Electric  5 Seats   
2737        2022 Tata Nexon EV XZ Plus Dark Edition  Electric  5 Seats   
2738        2022 Tata Nexon EV XZ Plus Dark Edition  Electric  5 Seats   
2931    2023 Tata Tiago EV XZ Plus Tech LUX LR ACFC  Electric  5 Seats   
3053        2023 Mahindra XUV400 EV EL Fast Charger  Electric  5 Seats   
3293                     2021 Tata Nexon EV XZ Plus  Electric  5 Seats   
3294                     2021 Tata Nexon EV XZ Plus  Electric  5 Seats   
3317                 2020 Tata Nexon EV XZ Plus LUX  Electric  5 Seats   
3487                     2023 Tata Nexon EV XZ Plus  Electric  5 Seats   
3832           2023 Tata Nexon EV Empowered Plus LR  Electric  5 Seats   
3969                  2024 Tata Tiago EV XZ Plus LR  Electric  5 Seats   
3978                       2023 Tata Tiago EV XT LR  Electric  5 Seats   
4091                    2025 Mahindra BE 6 Pack One  Electric  5 Seats   
4233                      2023 Hyundai Kona Premium  Electric  5 Seats   
4316                     2022 Tata Nexon EV XZ Plus  Electric  5 Seats   
4339                      2023 Hyundai Kona Premium  Electric  5 Seats   
4615                   2023 Mini Cooper SE Electric  Electric  4 Seats   
4637                   2024 Mini Cooper SE Electric  Electric  4 Seats   
4831           2024 Tata Nexon EV Empowered Plus 45  Electric  5 Seats   
4854                 2020 Tata Nexon EV XZ Plus LUX  Electric  5 Seats   
4909                    1991 Maruti Gypsy MG410W HT    Petrol  8 Seats   
4949                       2024 Tata Tiago EV XT LR  Electric  5 Seats   
5449           2024 Tata Nexon EV Empowered Plus LR  Electric  5 Seats   
5457                2024 Tata Punch EV Adventure LR  Electric  5 Seats   
5480                    2022 Audi e-tron 55 Quattro  Electric  5 Seats   
5506                           2023 BMW iX xDrive40  Electric  5 Seats   
5735                     2025 MG Windsor EV Essence  Electric  5 Seats   
5771                          2023 MG Comet EV Play  Electric  4 Seats   
5782           2024 Tata Nexon EV Empowered Plus LR  Electric  5 Seats   
5887                       2023 Citroen eC3 Feel DT  Electric  5 Seats   
5936           2021 Tata Tigor EV XZ Plus Dual Tone  Electric  5 Seats   
6116                     2022 Tata Tigor EV XZ Plus  Electric  5 Seats   
6371                        2012 Toyota Etios GD SP    Diesel  5 Seats   
6372                        2023 MG ZS EV Exclusive  Electric  5 Seats   
6485                      2023 Hyundai Kona

In [95]:
# Making the NaN values to '0' for rows with electric fuel_type
df.loc[(df['fuel_type'] == 'Electric') & (df['engine_displacement'].isna()),'engine_displacement'] = 0


In [96]:
# filling the missing values manually for remaining
engine_updates = {
    4909: 1298,   # Maruti Gypsy MG410W HT
    6371: 1364,   # Toyota Etios GD SP
    6915: 999,    # Hyundai Santro GLS II Euro II
    9343: 1396    # Hyundai i20 Sportz AT 1.4
}

for idx, cc in engine_updates.items():
    df.loc[idx, 'engine_displacement'] = cc

In [97]:
df['engine_displacement'] = df['engine_displacement'].astype('int32')

In [98]:
df.rename(columns={
'engine_displacement' : 'engine(cc)'
},inplace=True)

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10224 entries, 0 to 10223
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype   
---  ------             --------------  -----   
 0   vehicle_name       10224 non-null  object  
 1   fuel_type          10224 non-null  object  
 2   seats              10224 non-null  object  
 3   kms_driven         10224 non-null  int64   
 4   ownership          10224 non-null  category
 5   engine(cc)         10224 non-null  int32   
 6   transmission_type  10224 non-null  object  
 7   engine_power       7098 non-null   object  
 8   drive_type         2247 non-null   object  
 9   new_vehicle_price  10224 non-null  object  
 10  vehicle_price      10224 non-null  object  
 11  other_features     10224 non-null  object  
 12  mileage(kmpl)      6891 non-null   float64 
 13  registration_year  10224 non-null  int64   
 14  brand              10224 non-null  object  
 15  model              10224 non-null  object  
 16  rto_state

#### transmission_type :

In [100]:
df.head()

vehicle_name fuel_type    seats  kms_driven  \
0                    2013 Toyota Etios GD    Diesel  5 Seats      150000   
1                    2024 Toyota Glanza V    Petrol  5 Seats       10000   
2           2017 Hyundai Creta 1.4 E Plus    Diesel  5 Seats       75000   
3  2011 Volkswagen Vento Diesel Trendline    Diesel  5 Seats      160000   
4             2014 Hyundai Verna 1.6 CRDI    Diesel  5 Seats      120000   

      ownership  engine(cc) transmission_type engine_power drive_type  \
0  Fourth Owner        1364            Manual          NaN        NaN   
1   First Owner        1197            Manual          NaN        NaN   
2   First Owner        1396            Manual          NaN        NaN   
3   Third Owner        1598            Manual    103.6 bhp        NaN   
4   First Owner        1582            Manual    126.3 bhp        NaN   

           new_vehicle_price               vehicle_price  \
0   New Car Price ₹8.05 Lakh                 ₹2.60 Lakh    
1  New Car Price ₹11.28 Lakh                 ₹9.40 Lakh    
2  New Car Price ₹11.86 Lakh  ₹6.25 Lakh Make Your Offer   
3  New Car Price ₹10.05 Lakh                 ₹1.40 Lakh    
4  New Car Price ₹11.87 Lakh                    ₹4 Lakh    

                                     other_features  mileage(kmpl)  \
0                                                []            NaN   
1                                                []            NaN   
2                                                []            NaN   
3                               ['Parking Sensors']          20.54   
4  ['Automatic Climate Control', 'Parking Sensors']          22.32   

   registration_year       brand   model      rto_state  
0               2013      Toyota   Etios      Rajasthan  
1               2024      Toyota  Glanza         Punjab  
2               2017     Hyundai   Creta        Haryana  
3               2011  Volkswagen   Vento         Punjab  
4               2014     Hyundai   Verna  Uttar Pradesh

In [101]:
df['transmission_type'].value_counts()

transmission_type
Manual       8397
Automatic    1827
Name: count, dtype: int64

In [102]:
df.isnull().sum()

vehicle_name            0
fuel_type               0
seats                   0
kms_driven              0
ownership               0
engine(cc)              0
transmission_type       0
engine_power         3126
drive_type           7977
new_vehicle_price       0
vehicle_price           0
other_features          0
mileage(kmpl)        3333
registration_year       0
brand                   0
model                   0
rto_state               0
dtype: int64

In [103]:
df['transmission_type'] = df['transmission_type'].astype('category')

#### Engine power :

In [104]:
df.head()

vehicle_name fuel_type    seats  kms_driven  \
0                    2013 Toyota Etios GD    Diesel  5 Seats      150000   
1                    2024 Toyota Glanza V    Petrol  5 Seats       10000   
2           2017 Hyundai Creta 1.4 E Plus    Diesel  5 Seats       75000   
3  2011 Volkswagen Vento Diesel Trendline    Diesel  5 Seats      160000   
4             2014 Hyundai Verna 1.6 CRDI    Diesel  5 Seats      120000   

      ownership  engine(cc) transmission_type engine_power drive_type  \
0  Fourth Owner        1364            Manual          NaN        NaN   
1   First Owner        1197            Manual          NaN        NaN   
2   First Owner        1396            Manual          NaN        NaN   
3   Third Owner        1598            Manual    103.6 bhp        NaN   
4   First Owner        1582            Manual    126.3 bhp        NaN   

           new_vehicle_price               vehicle_price  \
0   New Car Price ₹8.05 Lakh                 ₹2.60 Lakh    
1  New Car Price ₹11.28 Lakh                 ₹9.40 Lakh    
2  New Car Price ₹11.86 Lakh  ₹6.25 Lakh Make Your Offer   
3  New Car Price ₹10.05 Lakh                 ₹1.40 Lakh    
4  New Car Price ₹11.87 Lakh                    ₹4 Lakh    

                                     other_features  mileage(kmpl)  \
0                                                []            NaN   
1                                                []            NaN   
2                                                []            NaN   
3                               ['Parking Sensors']          20.54   
4  ['Automatic Climate Control', 'Parking Sensors']          22.32   

   registration_year       brand   model      rto_state  
0               2013      Toyota   Etios      Rajasthan  
1               2024      Toyota  Glanza         Punjab  
2               2017     Hyundai   Creta        Haryana  
3               2011  Volkswagen   Vento         Punjab  
4               2014     Hyundai   Verna  Uttar Pradesh

In [105]:
df['engine_power'].value_counts()

engine_power
81.80 bhp      295
74 bhp         242
88.5 bhp       179
88.50 bhp      176
81.86 bhp      167
67.04 bhp      147
67 bhp         132
82 bhp         130
47.3 bhp       118
140 bhp        114
98.6 bhp       105
68.05 bhp      100
67.1 bhp       100
88.7 bhp        97
67.05 bhp       96
126.2 bhp       91
65.71 bhp       90
55.2 bhp        82
46.3 bhp        82
85.8 bhp        80
71.01 bhp       79
78.9 bhp        75
88.76 bhp       74
62.1 bhp        72
101.64 bhp      69
113.98 bhp      65
86.63 bhp       64
83.1 bhp        64
167.67 bhp      64
118.35 bhp      63
113.43 bhp      63
100 bhp         61
73.9 bhp        60
47.33 bhp       58
88.73 bhp       54
113.18 bhp      53
70 bhp          53
108.5 bhp       53
69 bhp          53
121.3 bhp       50
103.26 bhp      48
81.83 bhp       47
141 bhp         46
98.63 bhp       44
117.3 bhp       43
113.42 bhp      42
74.96 bhp       41
130 bhp         41
120 bhp         39
147.51 bhp      39
74.02 bhp       38
118.36 bhp      38

In [106]:
df.isnull().sum()/len(df)*100

vehicle_name          0.000000
fuel_type             0.000000
seats                 0.000000
kms_driven            0.000000
ownership             0.000000
engine(cc)            0.000000
transmission_type     0.000000
engine_power         30.575117
drive_type           78.022300
new_vehicle_price     0.000000
vehicle_price         0.000000
other_features        0.000000
mileage(kmpl)        32.599765
registration_year     0.000000
brand                 0.000000
model                 0.000000
rto_state             0.000000
dtype: float64

In [107]:
df['engine_power'] = df['engine_power'].str.replace('bhp','').astype('Float64')

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10224 entries, 0 to 10223
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype   
---  ------             --------------  -----   
 0   vehicle_name       10224 non-null  object  
 1   fuel_type          10224 non-null  object  
 2   seats              10224 non-null  object  
 3   kms_driven         10224 non-null  int64   
 4   ownership          10224 non-null  category
 5   engine(cc)         10224 non-null  int32   
 6   transmission_type  10224 non-null  category
 7   engine_power       7098 non-null   Float64 
 8   drive_type         2247 non-null   object  
 9   new_vehicle_price  10224 non-null  object  
 10  vehicle_price      10224 non-null  object  
 11  other_features     10224 non-null  object  
 12  mileage(kmpl)      6891 non-null   float64 
 13  registration_year  10224 non-null  int64   
 14  brand              10224 non-null  object  
 15  model              10224 non-null  object  
 16  rto_state

#### drive_type :

In [109]:
df.head()

vehicle_name fuel_type    seats  kms_driven  \
0                    2013 Toyota Etios GD    Diesel  5 Seats      150000   
1                    2024 Toyota Glanza V    Petrol  5 Seats       10000   
2           2017 Hyundai Creta 1.4 E Plus    Diesel  5 Seats       75000   
3  2011 Volkswagen Vento Diesel Trendline    Diesel  5 Seats      160000   
4             2014 Hyundai Verna 1.6 CRDI    Diesel  5 Seats      120000   

      ownership  engine(cc) transmission_type  engine_power drive_type  \
0  Fourth Owner        1364            Manual          <NA>        NaN   
1   First Owner        1197            Manual          <NA>        NaN   
2   First Owner        1396            Manual          <NA>        NaN   
3   Third Owner        1598            Manual         103.6        NaN   
4   First Owner        1582            Manual         126.3        NaN   

           new_vehicle_price               vehicle_price  \
0   New Car Price ₹8.05 Lakh                 ₹2.60 Lakh    
1  New Car Price ₹11.28 Lakh                 ₹9.40 Lakh    
2  New Car Price ₹11.86 Lakh  ₹6.25 Lakh Make Your Offer   
3  New Car Price ₹10.05 Lakh                 ₹1.40 Lakh    
4  New Car Price ₹11.87 Lakh                    ₹4 Lakh    

                                     other_features  mileage(kmpl)  \
0                                                []            NaN   
1                                                []            NaN   
2                                                []            NaN   
3                               ['Parking Sensors']          20.54   
4  ['Automatic Climate Control', 'Parking Sensors']          22.32   

   registration_year       brand   model      rto_state  
0               2013      Toyota   Etios      Rajasthan  
1               2024      Toyota  Glanza         Punjab  
2               2017     Hyundai   Creta        Haryana  
3               2011  Volkswagen   Vento         Punjab  
4               2014     Hyundai   Verna  Uttar Pradesh

In [110]:
df.isnull().sum()/len(df)*100

vehicle_name          0.000000
fuel_type             0.000000
seats                 0.000000
kms_driven            0.000000
ownership             0.000000
engine(cc)            0.000000
transmission_type     0.000000
engine_power         30.575117
drive_type           78.022300
new_vehicle_price     0.000000
vehicle_price         0.000000
other_features        0.000000
mileage(kmpl)        32.599765
registration_year     0.000000
brand                 0.000000
model                 0.000000
rto_state             0.000000
dtype: float64

In [111]:
df['drive_type'].value_counts()

drive_type
FWD                 1374
RWD                  343
AWD                  166
4WD                  145
2WD                  117
4X4                   39
4X2                   36
RWD(with MTT)         11
4x2                    6
2 WD                   6
Four Whell Drive       1
4x4                    1
Permanent AWD          1
All Wheel Drive        1
Name: count, dtype: int64

In [112]:
# dropping the col because it has 78% missing values
df.drop(columns=['drive_type'],axis=1,inplace=True)

#### New_vehicle_price :

In [113]:
df.head()

vehicle_name fuel_type    seats  kms_driven  \
0                    2013 Toyota Etios GD    Diesel  5 Seats      150000   
1                    2024 Toyota Glanza V    Petrol  5 Seats       10000   
2           2017 Hyundai Creta 1.4 E Plus    Diesel  5 Seats       75000   
3  2011 Volkswagen Vento Diesel Trendline    Diesel  5 Seats      160000   
4             2014 Hyundai Verna 1.6 CRDI    Diesel  5 Seats      120000   

      ownership  engine(cc) transmission_type  engine_power  \
0  Fourth Owner        1364            Manual          <NA>   
1   First Owner        1197            Manual          <NA>   
2   First Owner        1396            Manual          <NA>   
3   Third Owner        1598            Manual         103.6   
4   First Owner        1582            Manual         126.3   

           new_vehicle_price               vehicle_price  \
0   New Car Price ₹8.05 Lakh                 ₹2.60 Lakh    
1  New Car Price ₹11.28 Lakh                 ₹9.40 Lakh    
2  New Car Price ₹11.86 Lakh  ₹6.25 Lakh Make Your Offer   
3  New Car Price ₹10.05 Lakh                 ₹1.40 Lakh    
4  New Car Price ₹11.87 Lakh                    ₹4 Lakh    

                                     other_features  mileage(kmpl)  \
0                                                []            NaN   
1                                                []            NaN   
2                                                []            NaN   
3                               ['Parking Sensors']          20.54   
4  ['Automatic Climate Control', 'Parking Sensors']          22.32   

   registration_year       brand   model      rto_state  
0               2013      Toyota   Etios      Rajasthan  
1               2024      Toyota  Glanza         Punjab  
2               2017     Hyundai   Creta        Haryana  
3               2011  Volkswagen   Vento         Punjab  
4               2014     Hyundai   Verna  Uttar Pradesh

In [114]:
df.isnull().sum()

vehicle_name            0
fuel_type               0
seats                   0
kms_driven              0
ownership               0
engine(cc)              0
transmission_type       0
engine_power         3126
new_vehicle_price       0
vehicle_price           0
other_features          0
mileage(kmpl)        3333
registration_year       0
brand                   0
model                   0
rto_state               0
dtype: int64

In [116]:
#extracting the price value and converting into flaot
import re


def convert_price(x):
    x = str(x)

    # --- Crore format ---
    crore_match = re.search(r'₹\s*([\d\.]+)\s*Crore', x, re.IGNORECASE)
    if crore_match:
        return float(crore_match.group(1)) * 10000000  # 1 Crore = 1 Cr * 1 Crore

    # --- Lakh format ---
    lakh_match = re.search(r'₹\s*([\d\.]+)\s*Lakh', x, re.IGNORECASE)
    if lakh_match:
        return float(lakh_match.group(1)) * 100000     # 1 Lakh

    return np.nan
        

df['new_vehicle_price_rupees'] = df['new_vehicle_price'].apply(convert_price)

In [117]:
df.drop(columns=['new_vehicle_price'],axis=1,inplace=True)

In [118]:
df.isnull().sum()

vehicle_name                   0
fuel_type                      0
seats                          0
kms_driven                     0
ownership                      0
engine(cc)                     0
transmission_type              0
engine_power                3126
vehicle_price                  0
other_features                 0
mileage(kmpl)               3333
registration_year              0
brand                          0
model                          0
rto_state                      0
new_vehicle_price_rupees       0
dtype: int64

#### Vehicle_price :

In [119]:
df.head()

vehicle_name fuel_type    seats  kms_driven  \
0                    2013 Toyota Etios GD    Diesel  5 Seats      150000   
1                    2024 Toyota Glanza V    Petrol  5 Seats       10000   
2           2017 Hyundai Creta 1.4 E Plus    Diesel  5 Seats       75000   
3  2011 Volkswagen Vento Diesel Trendline    Diesel  5 Seats      160000   
4             2014 Hyundai Verna 1.6 CRDI    Diesel  5 Seats      120000   

      ownership  engine(cc) transmission_type  engine_power  \
0  Fourth Owner        1364            Manual          <NA>   
1   First Owner        1197            Manual          <NA>   
2   First Owner        1396            Manual          <NA>   
3   Third Owner        1598            Manual         103.6   
4   First Owner        1582            Manual         126.3   

                vehicle_price  \
0                 ₹2.60 Lakh    
1                 ₹9.40 Lakh    
2  ₹6.25 Lakh Make Your Offer   
3                 ₹1.40 Lakh    
4                    ₹4 Lakh    

                                     other_features  mileage(kmpl)  \
0                                                []            NaN   
1                                                []            NaN   
2                                                []            NaN   
3                               ['Parking Sensors']          20.54   
4  ['Automatic Climate Control', 'Parking Sensors']          22.32   

   registration_year       brand   model      rto_state  \
0               2013      Toyota   Etios      Rajasthan   
1               2024      Toyota  Glanza         Punjab   
2               2017     Hyundai   Creta        Haryana   
3               2011  Volkswagen   Vento         Punjab   
4               2014     Hyundai   Verna  Uttar Pradesh   

   new_vehicle_price_rupees  
0                  805000.0  
1                 1128000.0  
2                 1186000.0  
3                 1005000.0  
4                 1187000.0

In [120]:
df.isnull().sum()

vehicle_name                   0
fuel_type                      0
seats                          0
kms_driven                     0
ownership                      0
engine(cc)                     0
transmission_type              0
engine_power                3126
vehicle_price                  0
other_features                 0
mileage(kmpl)               3333
registration_year              0
brand                          0
model                          0
rto_state                      0
new_vehicle_price_rupees       0
dtype: int64

In [121]:
# extracting only price value from the col and making it into rupees
def convert_price_to_rupees(x):
    x = str(x)

    # Remove "Make Your Offer"
    x = x.replace("Make Your Offer", "").strip()

    # Handle Crore
    crore_match = re.search(r"₹\s*([\d\.]+)\s*Crore", x, re.IGNORECASE)
    if crore_match:
        return float(crore_match.group(1)) * 10000000    # 1 Crore = 1 Cr = 1e7

    # Handle Lakh
    lakh_match = re.search(r"₹\s*([\d\.]+)\s*Lakh", x, re.IGNORECASE)
    if lakh_match:
        return float(lakh_match.group(1)) * 100000       # 1 Lakh = 1e5

    # Handle Thousand
    thousand_match = re.search(r"₹\s*([\d\.]+)\s*Thousand", x, re.IGNORECASE)
    if thousand_match:
        return float(thousand_match.group(1)) * 1000     # 1 Thousand = 1e3

    # Very rare: values like "₹1 Crore" with no number
    if "₹" in x:
        numeric = re.findall(r"[\d\.]+", x)
        if numeric:
            return float(numeric[0]) * 1  # direct assume rupees (rare)

    return np.nan   # if no pattern matches


# APPLY TO COLUMN
df["vehicle_price_rupees"] = df["vehicle_price"].apply(convert_price_to_rupees)


In [122]:
df.drop(columns=['vehicle_price'],axis=1,inplace=True)

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10224 entries, 0 to 10223
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype   
---  ------                    --------------  -----   
 0   vehicle_name              10224 non-null  object  
 1   fuel_type                 10224 non-null  object  
 2   seats                     10224 non-null  object  
 3   kms_driven                10224 non-null  int64   
 4   ownership                 10224 non-null  category
 5   engine(cc)                10224 non-null  int32   
 6   transmission_type         10224 non-null  category
 7   engine_power              7098 non-null   Float64 
 8   other_features            10224 non-null  object  
 9   mileage(kmpl)             6891 non-null   float64 
 10  registration_year         10224 non-null  int64   
 11  brand                     10224 non-null  object  
 12  model                     10224 non-null  object  
 13  rto_state                 10224 non-null  object  


#### Other features :

In [124]:
df.head()

vehicle_name fuel_type    seats  kms_driven  \
0                    2013 Toyota Etios GD    Diesel  5 Seats      150000   
1                    2024 Toyota Glanza V    Petrol  5 Seats       10000   
2           2017 Hyundai Creta 1.4 E Plus    Diesel  5 Seats       75000   
3  2011 Volkswagen Vento Diesel Trendline    Diesel  5 Seats      160000   
4             2014 Hyundai Verna 1.6 CRDI    Diesel  5 Seats      120000   

      ownership  engine(cc) transmission_type  engine_power  \
0  Fourth Owner        1364            Manual          <NA>   
1   First Owner        1197            Manual          <NA>   
2   First Owner        1396            Manual          <NA>   
3   Third Owner        1598            Manual         103.6   
4   First Owner        1582            Manual         126.3   

                                     other_features  mileage(kmpl)  \
0                                                []            NaN   
1                                                []            NaN   
2                                                []            NaN   
3                               ['Parking Sensors']          20.54   
4  ['Automatic Climate Control', 'Parking Sensors']          22.32   

   registration_year       brand   model      rto_state  \
0               2013      Toyota   Etios      Rajasthan   
1               2024      Toyota  Glanza         Punjab   
2               2017     Hyundai   Creta        Haryana   
3               2011  Volkswagen   Vento         Punjab   
4               2014     Hyundai   Verna  Uttar Pradesh   

   new_vehicle_price_rupees  vehicle_price_rupees  
0                  805000.0              260000.0  
1                 1128000.0              940000.0  
2                 1186000.0              625000.0  
3                 1005000.0              140000.0  
4                 1187000.0              400000.0

In [127]:
df['has_parking_sensors'] = df['other_features'].str.contains('Parking Sensors').apply(lambda x: 1 if x==True else 0)

In [131]:
df['has_automatic_climate_control'] = df['other_features'].str.contains('Automatic Climate Control').apply(lambda x: 1 if x==True else 0)

In [136]:
df['has_rear_ac_vents'] = df['other_features'].str.contains('Rear AC Vents').apply(lambda x: 1 if x==True else 0)

In [140]:
df['has_central_locking'] = df['other_features'].str.contains('Central Locking').apply(lambda x: 1 if x==True else 0)

In [141]:
df['has_air_purifier'] = df['other_features'].str.contains('Air Purifier').apply(lambda x: 1 if x==True else 0)

In [145]:
df.drop(columns=['has_keyless_entry'],axis=1,inplace=True)

In [146]:
df.head()

vehicle_name fuel_type    seats  kms_driven  \
0                    2013 Toyota Etios GD    Diesel  5 Seats      150000   
1                    2024 Toyota Glanza V    Petrol  5 Seats       10000   
2           2017 Hyundai Creta 1.4 E Plus    Diesel  5 Seats       75000   
3  2011 Volkswagen Vento Diesel Trendline    Diesel  5 Seats      160000   
4             2014 Hyundai Verna 1.6 CRDI    Diesel  5 Seats      120000   

      ownership  engine(cc) transmission_type  engine_power  \
0  Fourth Owner        1364            Manual          <NA>   
1   First Owner        1197            Manual          <NA>   
2   First Owner        1396            Manual          <NA>   
3   Third Owner        1598            Manual         103.6   
4   First Owner        1582            Manual         126.3   

                                     other_features  mileage(kmpl)  ...  \
0                                                []            NaN  ...   
1                                                []            NaN  ...   
2                                                []            NaN  ...   
3                               ['Parking Sensors']          20.54  ...   
4  ['Automatic Climate Control', 'Parking Sensors']          22.32  ...   

        brand   model      rto_state new_vehicle_price_rupees  \
0      Toyota   Etios      Rajasthan                 805000.0   
1      Toyota  Glanza         Punjab                1128000.0   
2     Hyundai   Creta        Haryana                1186000.0   
3  Volkswagen   Vento         Punjab                1005000.0   
4     Hyundai   Verna  Uttar Pradesh                1187000.0   

   vehicle_price_rupees  has_parking_sensors  has_automatic_climate_control  \
0              260000.0                    0                              0   
1              940000.0                    0                              0   
2              625000.0                    0                              0   
3              140000.0                    1                              0   
4              400000.0                    1                              1   

   has_rear_ac_vents  has_central_locking  has_air_purifier  
0                  0                    0                 0  
1                  0                    0                 0  
2                  0                    0                 0  
3                  0                    0                 0  
4                  0                    0                 0  

[5 rows x 21 columns]

In [148]:
df.drop(columns=['vehicle_name','other_features'],axis=1,inplace=True)

In [150]:
df1 = df[['brand','model','registration_year','fuel_type','seats','rto_state','transmission_type','ownership','engine(cc)','kms_driven','engine_power','mileage(kmpl)','has_parking_sensors','has_automatic_climate_control','has_rear_ac_vents','has_central_locking','has_air_purifier','new_vehicle_price_rupees','vehicle_price_rupees']]

In [154]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10224 entries, 0 to 10223
Data columns (total 19 columns):
 #   Column                         Non-Null Count  Dtype   
---  ------                         --------------  -----   
 0   brand                          10224 non-null  object  
 1   model                          10224 non-null  object  
 2   registration_year              10224 non-null  int64   
 3   fuel_type                      10224 non-null  object  
 4   seats                          10224 non-null  object  
 5   rto_state                      10224 non-null  object  
 6   transmission_type              10224 non-null  category
 7   ownership                      10224 non-null  category
 8   engine(cc)                     10224 non-null  int32   
 9   kms_driven                     10224 non-null  int64   
 10  engine_power                   7098 non-null   Float64 
 11  mileage(kmpl)                  6891 non-null   float64 
 12  has_parking_sensors            10224 

#### Mileage(kmpl) & Engine_power :

In [9]:
df.isnull().sum()/len(df)*100

brand                             0.000000
model                             0.000000
registration_year                 0.000000
fuel_type                         0.000000
seats                             0.000000
rto_state                         0.000000
transmission_type                 0.000000
ownership                         0.000000
engine(cc)                        0.000000
kms_driven                        0.000000
engine_power                     30.575117
mileage(kmpl)                    32.599765
has_parking_sensors               0.000000
has_automatic_climate_control     0.000000
has_rear_ac_vents                 0.000000
has_central_locking               0.000000
has_air_purifier                  0.000000
new_vehicle_price_rupees          0.000000
vehicle_price_rupees              0.000000
dtype: float64

In [10]:
df.head()

brand   model  registration_year fuel_type    seats      rto_state  \
0      Toyota   Etios               2013    Diesel  5 Seats      Rajasthan   
1      Toyota  Glanza               2024    Petrol  5 Seats         Punjab   
2     Hyundai   Creta               2017    Diesel  5 Seats        Haryana   
3  Volkswagen   Vento               2011    Diesel  5 Seats         Punjab   
4     Hyundai   Verna               2014    Diesel  5 Seats  Uttar Pradesh   

  transmission_type     ownership  engine(cc)  kms_driven  engine_power  \
0            Manual  Fourth Owner        1364      150000           NaN   
1            Manual   First Owner        1197       10000           NaN   
2            Manual   First Owner        1396       75000           NaN   
3            Manual   Third Owner        1598      160000         103.6   
4            Manual   First Owner        1582      120000         126.3   

   mileage(kmpl)  has_parking_sensors  has_automatic_climate_control  \
0            NaN                    0                              0   
1            NaN                    0                              0   
2            NaN                    0                              0   
3          20.54                    1                              0   
4          22.32                    1                              1   

   has_rear_ac_vents  has_central_locking  has_air_purifier  \
0                  0                    0                 0   
1                  0                    0                 0   
2                  0                    0                 0   
3                  0                    0                 0   
4                  0                    0                 0   

   new_vehicle_price_rupees  vehicle_price_rupees  
0                  805000.0              260000.0  
1                 1128000.0              940000.0  
2                 1186000.0              625000.0  
3                 1005000.0              140000.0  
4                 1187000.0              400000.0

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10224 entries, 0 to 10223
Data columns (total 19 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   brand                          10224 non-null  object 
 1   model                          10224 non-null  object 
 2   registration_year              10224 non-null  int64  
 3   fuel_type                      10224 non-null  object 
 4   seats                          10224 non-null  object 
 5   rto_state                      10224 non-null  object 
 6   transmission_type              10224 non-null  object 
 7   ownership                      10224 non-null  object 
 8   engine(cc)                     10224 non-null  int64  
 9   kms_driven                     10224 non-null  int64  
 10  engine_power                   7098 non-null   float64
 11  mileage(kmpl)                  6891 non-null   float64
 12  has_parking_sensors            10224 non-null  int6

In [17]:
df['brand'] = df['brand'].astype('category')
df['fuel_type'] = df['fuel_type'].astype('category')
df['seats'] = df['seats'].astype('category')
df['rto_state'] = df['rto_state'].astype('category')
df['ownership'] = df['ownership'].astype('category')
df['transmission_type'] = df['transmission_type'].astype('category')
df['has_parking_sensors'] = df['has_parking_sensors'].astype('int8')
df['has_automatic_climate_control'] = df['has_automatic_climate_control'].astype('int8')
df['has_rear_ac_vents'] = df['has_rear_ac_vents'].astype('int8')
df['has_air_purifier'] = df['has_air_purifier'].astype('int8')
df['has_central_locking'] = df['has_central_locking'].astype('int8')

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10224 entries, 0 to 10223
Data columns (total 19 columns):
 #   Column                         Non-Null Count  Dtype   
---  ------                         --------------  -----   
 0   brand                          10224 non-null  category
 1   model                          10224 non-null  object  
 2   registration_year              10224 non-null  int64   
 3   fuel_type                      10224 non-null  category
 4   seats                          10224 non-null  category
 5   rto_state                      10224 non-null  category
 6   transmission_type              10224 non-null  category
 7   ownership                      10224 non-null  category
 8   engine(cc)                     10224 non-null  int64   
 9   kms_driven                     10224 non-null  int64   
 10  engine_power                   7098 non-null   float64 
 11  mileage(kmpl)                  6891 non-null   float64 
 12  has_parking_sensors            10224 

In [20]:
df.head()

brand   model  registration_year fuel_type    seats      rto_state  \
0      Toyota   Etios               2013    Diesel  5 Seats      Rajasthan   
1      Toyota  Glanza               2024    Petrol  5 Seats         Punjab   
2     Hyundai   Creta               2017    Diesel  5 Seats        Haryana   
3  Volkswagen   Vento               2011    Diesel  5 Seats         Punjab   
4     Hyundai   Verna               2014    Diesel  5 Seats  Uttar Pradesh   

  transmission_type     ownership  engine(cc)  kms_driven  engine_power  \
0            Manual  Fourth Owner        1364      150000           NaN   
1            Manual   First Owner        1197       10000           NaN   
2            Manual   First Owner        1396       75000           NaN   
3            Manual   Third Owner        1598      160000         103.6   
4            Manual   First Owner        1582      120000         126.3   

   mileage(kmpl)  has_parking_sensors  has_automatic_climate_control  \
0            NaN                    0                              0   
1            NaN                    0                              0   
2            NaN                    0                              0   
3          20.54                    1                              0   
4          22.32                    1                              1   

   has_rear_ac_vents  has_central_locking  has_air_purifier  \
0                  0                    0                 0   
1                  0                    0                 0   
2                  0                    0                 0   
3                  0                    0                 0   
4                  0                    0                 0   

   new_vehicle_price_rupees  vehicle_price_rupees  
0                  805000.0              260000.0  
1                 1128000.0              940000.0  
2                 1186000.0              625000.0  
3                 1005000.0              140000.0  
4                 1187000.0              400000.0

In [21]:
#saving the df with same dtypes
import pickle

with open("original_data_without_imputation.pkl", "wb") as f:
    pickle.dump(df, f)